### ISSUE TITLE
Your netrc is showing

### ISSUE THREAD

**Issue by JamesAwesome** [RichardKnop/machinery#1]
Just FYI :(

**Comment by vanhalt** [comment]
:(

**Comment by vjeantet** [comment]
Maybe one of you can use it to remove this sensitive information :-/ ? And change password ?

**Comment by RichardKnop** [comment]
This is needed for TravisCI to work. The token is read only, so it should be safe. I didn't find any other way to make TravisCI work.

**Comment by JamesAwesome** [comment]
Personally I would see if I could encrypt it and export it as a variable and build the .netrc on the fly. It's read only but it does give us read access to all your repos...

**Comment by RichardKnop** [comment]
Thanks. I used environment variable for that ;)

**Comment by JamesAwesome** [comment]
Glad I could help. :+1: :smile:
