### ISSUE TITLE
Setting the concurrency level for worker?

### ISSUE THREAD

**Issue by oleksandr** [RichardKnop/machinery#105]
As far as I can see it's not possible at the moment to set the size of worker's pool? How do you plan to throttle incoming tasks to protect the resources?

**Comment by RichardKnop** [comment]
@oleksandr Currently this is not possible. I would like to add this feature though if I have enough time as I think it's important. Feel free to submit a PR if you have a working implementation of worker concurrency.

**Comment by oleksandr** [comment]
@RichardKnop OK, this is something I'm currently looking at and would love to submit PR soon.

**Comment by RichardKnop** [comment]
@oleksandr Cheers. Looking forward to it!

**Comment by hphilipps** [comment]
@oleksandr I think PR #111 is implementing what you asked for and is merged with master.
