### ISSUE TITLE
Launch machinery worker within application?

### ISSUE THREAD

**Issue by catherinetcai** [RichardKnop/machinery#106]
I'm trying to use machinery within a larger application. I was wondering if there was any way to launch machinery workers within the application, so that it can send and work on applications at the same time...

Or am I fundamentally misusing machinery?

**Comment by RichardKnop** [comment]
This should be possible. You can create a worker and launch it inside your application.

```go
worker := server.NewWorker("worker_name")
err := worker.Launch()
if err != nil {
  // do something with the error
}
```

You could launch it inside a goroutine if you wanted to.

However I would probably run it as a separate process. Imagine this library like Python's `celery`.

You would run celery workers as separate process and send celery tasks to them from main application.

**Comment by catherinetcai** [comment]
@RichardKnop - Thanks for the quick response! I thought that would be the case, so I set it up, but I seem to be having a few issues...

I start a new worker inside my application and I see that it connects to Redis (using both Redis as a broker and a backend), and it hangs unless I launch it in a separate goroutine: 

`machinery: worker.go:28: - Broker: redis://localhost:6379
machinery: worker.go:29: - ResultBackend: redis://localhost:6379
machinery: worker.go:30: - Exchange:
machinery: worker.go:31: - ExchangeType:
machinery: worker.go:32: - DefaultQueue: machinery-test
machinery: worker.go:33: - BindingKey:
machinery: redis.go:86: [*] Waiting for messages. To exit press CTRL+C`

When I have it spun up in another Goroutine, it seems to hang once I register more than four tasks. For whatever reason, I see the messages get sent, but they get stuck in the PENDING state. Is there some sort of deadlock going on?

**Comment by RichardKnop** [comment]
@catherinetcai There could be some deadlock going on, I am not sure. Have you had any luck debugging this to see where the issue is coming from? I will look once I have some free time.

**Comment by catherinetcai** [comment]
@RichardKnop - Looks like the only way I've been able to resolve this has been to create a slice of workers, and then instantiate these workers in a goroutine.
