### ISSUE TITLE
Creating workers with different configurations

### ISSUE THREAD

**Issue by gofort** [RichardKnop/machinery#107]
Exchange, Exchange type, Default queue, Queue Binding Arguments and Binding Key, tasks are worker configurations, not server. For now we can't create worker which will use another queue except default, because we need to create new server instance and create worker from it. I think that only broker, result backend, result expire in and TLS configurations should be in servers config struct.
And when you create new worker from server instance, worker should handle its own tasks and use his queue which can differ from other workers configurations connected to this server. Also for every worker concurrency limit option should be added.

**Comment by RichardKnop** [comment]
@gofort You are correct. The configuration is one of the main areas that needs refactoring if I get enough time.

I was thinking of different way to refactor config. What you mention seems like a good approach. Also the format of connection strings is a bit ambiguous so I was looking at refactoring that as well.

If you would like to contribute and submit a PR with refactor/more sensible structure, it would help this project a lot.
