### ISSUE TITLE
Add new brokers and backends

### ISSUE THREAD

**Issue by m0sth8** [RichardKnop/machinery#11]
Hello @RichardKnop, I want to use my own broker (in memory broker) for testing purposes. 
Could you add methods to `Server` for set up broker and backend?

**Comment by RichardKnop** [comment]
@m0sth8 I have added setters and getters to Server. Is this good enough for testing?

https://github.com/RichardKnop/machinery/blob/master/v1/server.go#L49

**Comment by m0sth8** [comment]
Thanks, It's enough for me.
