### ISSUE TITLE
Is machinery ready for using it in production?

### ISSUE THREAD

**Issue by michaeltcoelho** [RichardKnop/machinery#110]
Hey there! I came from python and its celery library for distributed messaging. Is there anyone using machinery in production already?

**Comment by bscott** [comment]
This project is still very young, doesn't seem to be ready for Production, but that's up to your needs and how critical they are.

**Comment by RichardKnop** [comment]
I am not aware of anybody using machinery in production. I know about multiple instances of people experimenting with it in development environments.

Of course, there might be somebody our there using it in production already :)

It would help the project if some companies or people actually used the library in their production environments, maybe on smaller scale to see how robust it is.

**Comment by seonixx** [comment]
Any updates/change of opinion on this (almost) a year on? Looking to implement this in production for a startup.
