### ISSUE TITLE
Using Machinery with Python Celery

### ISSUE THREAD

**Issue by marcsantiago** [RichardKnop/machinery#112]
I was curious as to whether or not I could use Machinery to communicate with python via celery. For example if I have a go webserver, can I send a task to the queuing system and then have a python script using celery execute that task and then retrieve the results with Go again?  I'm in the process of creating a hybrid system where all automations are done in python, but the web app is in Go. So I wanted to know whether or not I could use your tech as a sort of bridge between the two languages.

**Comment by RichardKnop** [comment]
@marcsantiago I am afraid this will not work at the moment. Machinery was inspired by celery when I originally wrote it but they are not identical, the format of messages is a bit different.

You could probably rework the library to use identical format to celery in which case it might work. Not sure that's worth the effort.

It might be trivial to send tasks to celery from Go just using the AMQP library and hand crafting the message format so celery understands it.
