### ISSUE TITLE
How to pass addition data to worker?

### ISSUE THREAD

**Issue by sergebezborodov** [RichardKnop/machinery#115]
Hello!

I want to pass Machinery server instance to worker, how can I do this?
My worker must set tasks to another workers.

Thank you

**Comment by RichardKnop** [comment]
@sergebezborodov Hi,

Sorry for late reply. Currently there is no way of doing it.

I am thinking about whether this is a good idea to implement such feature. I am not sure accessing server instance inside tasks is a good practice / idea.

This could lead to deadlocks within tasks potentially. I know you can do this with celery but it is advised against as it's a bad practice.

If there is a clean way to implement this, perhaps it could be added as optional feature.
