### ISSUE TITLE
How to retry failed tasks?

### ISSUE THREAD

**Issue by kartlee** [RichardKnop/machinery#116]
Hi,

Is there a way to configure the worker to retry the failed task at periodic interval and give up and report in the task queue status?

-Karthik

**Comment by kartlee** [comment]
I see a OnError callback in the task signature. I assume we can register a worker which can exclusively retry failed tasks? Is there a working example for this?

**Comment by RichardKnop** [comment]
@kartlee There isn't a way to configure machinery to retry failed tasks at the moment. You can set callback tasks (OnSuccess task will be called when task completes successfully, OnError task will be called when the task failed - and the error string will be first argument passed to it).

**Comment by kartlee** [comment]
Thanks Richard. Feel free to close it.

-Karthik

**Comment by dkiser** [comment]
This would be an AWESOME feature that aligns with a few key requirements of the system I'm looking to migrate away from (Celery in Python).

**Comment by kartlee** [comment]
Excellent. Looking forward for the change...

**Comment by foobargeez** [comment]
+1 retrying failed tasks will be pretty helpful.

**Comment by RichardKnop** [comment]
@kartlee @dkiser @foobargeez I have implemented a very basic retry logic: https://github.com/RichardKnop/machinery#retry-tasks
