### ISSUE TITLE
Using SQS Broker and S3 Results Backend.

### ISSUE THREAD

**Issue by siredwin** [RichardKnop/machinery#117]
I currently use Python Celery with SQS broker and S3 results backend in a production ready environment.  How hard will it be to create this configuration with machinery in go?  I am in the process of migrating everything to go.

**Comment by RichardKnop** [comment]
It would not be too difficult. But I guess it would require a week or two of work. You can look at interfaces in `brokers` and `backends` directories. You just need to implement them. And I would also add unit and integration tests.
