### ISSUE TITLE
more complex workflow?

### ISSUE THREAD

**Issue by yexiangyu** [RichardKnop/machinery#120]
Hi all, 

I'm designing a solution require to create a workflow with couple of steps constructed  by some group/chord/chain/task together. Is there any plan of this feature? Or should I implement it outside of machinery? Any suggestion will be welcomed.

Thanks for your great job at first, really wonderful piece of work.

**Comment by Blogoslov** [comment]
Hello yexiangyu,
yes I also  search such functionality at 'machinery' but it seems not available. Do you have any ideas how it can be done until it does not supported by 'machinery'?
