### ISSUE TITLE
Connection Reset By Peer

### ISSUE THREAD

**Issue by asimashfaq** [RichardKnop/machinery#123]
Why am getting this error "connection reset by the peer"

http://prntscr.com/ehqfop

When i wait for the task result it just crash the sender

**Comment by asimashfaq** [comment]
When ever i try to send 150+ task at once it  reset my connection

**Comment by Jolly23** [comment]
I have the same problem, have you fixed it?

**Comment by Jolly23** [comment]
I use `SendGroup` to send my tasks, when I send 10 tasks, it works well. However, if I send 100 tasks, it tells me `read tcp 127.0.0.1:56064->127.0.0.1:56379: read: connection reset by peer`.
I do not know how to solve this problem.

**Comment by Jolly23** [comment]
@RichardKnop Could you help us?
