### ISSUE TITLE
Disable prefect in rabbitmq for long running tasks 

### ISSUE THREAD

**Issue by macnibblet** [RichardKnop/machinery#126]
I was reading through the code and I noticed the rabbitmq broker pre-fetches three messages, which might be a concern for me with very many long running tasks encoding files.

**Comment by RichardKnop** [comment]
@macnibblet This could be added to config object so it's not hardcoded.

**Comment by RichardKnop** [comment]
@macnibblet I have added `prefetch_count` configuration option so you can now disable it via config (or set it to a low number such as 1 so each worker will only be processing one task at a time).

https://github.com/RichardKnop/machinery/blob/master/v1/config/config.go#L31
