### ISSUE TITLE
Suggestion: Support the nats.io as Messageing system

### ISSUE THREAD

**Issue by zfsamzfsam** [RichardKnop/machinery#133]
NATS  is a simple, high performance open source messaging system for cloud native applications, IoT messaging, and microservices architectures.
https://nats.io/

**Comment by RichardKnop** [comment]
@zfsamzfsam If you want to contribute, adding NATS broker would mean implementing this interface: https://github.com/RichardKnop/machinery/blob/master/v1/brokers/interfaces.go#L8

You can take a look at `AMQP` and `Redis` broker implementations to get some idea how it's done currently.

https://github.com/RichardKnop/machinery/blob/master/v1/brokers/amqp.go
https://github.com/RichardKnop/machinery/blob/master/v1/brokers/redis.go

How would you implement delayed tasks with `NATS`? Currently we finally got that working with both `AMQP` and `Redis` backends so any new brokers we add would have to support this feature to stay consistent.

**Comment by paulm17** [comment]
@zfsamzfsam It's been a while, but since no-one has approached this.  I want this as well, so will be working on it.  If I'm successful, PR to follow...

**Comment by paulm17** [comment]
Thought I would update.  I have Nats working for a Broker and I have MemSQL working as a backend, similarly to how memcache works.

	INFO: 2018/04/30 15:23:49 file.go:19 Successfully loaded config from file config.yml
	INFO: 2018/04/30 15:23:49 worker.go:43 Launching a worker with the following settings:
	INFO: 2018/04/30 15:23:49 worker.go:44 - Broker: nats://localhost:4222
	INFO: 2018/04/30 15:23:49 worker.go:45 - DefaultQueue: machinery_tasks
	INFO: 2018/04/30 15:23:49 worker.go:46 - ResultBackend: memsqlcache://root:f00b4r@tcp(192.168.0.28:3306)/machinery
	INFO: 2018/04/30 15:23:49 nats.go:45 [*] Waiting for messages. To exit press CTRL+C

Tomorrow, I will use NATS Streaming instead of the basic one.  As this includes things acknowledgements and might as well have it as close to the AMPQ implementation.

**Comment by Blogoslov** [comment]
> Thought I would update. I have Nats working for a Broker and I have a MemSQL cluster working as a backend, similarly to how memcache works.
> 
> ```
> INFO: 2018/04/30 15:23:49 file.go:19 Successfully loaded config from file config.yml
> INFO: 2018/04/30 15:23:49 worker.go:43 Launching a worker with the following settings:
> INFO: 2018/04/30 15:23:49 worker.go:44 - Broker: nats://localhost:4222
> INFO: 2018/04/30 15:23:49 worker.go:45 - DefaultQueue: machinery_tasks
> INFO: 2018/04/30 15:23:49 worker.go:46 - ResultBackend: memsqlcache://root:f00b4r@tcp(192.168.0.28:3306)/machinery
> INFO: 2018/04/30 15:23:49 nats.go:45 [*] Waiting for messages. To exit press CTRL+C
> ```
> Tomorrow, I will use NATS Streaming instead of the basic one. As this includes things acknowledgements and might as well have it as close to the AMPQ implementation.

Hello @paulm17 , how did you implemented NATS as a broker? Do you have its own machinery fork? I'm also interested in NATS as a broker. Could you please share your implementation?

**Comment by paulm17** [comment]
@Blogoslov Take a look here: https://github.com/paulm17/machinery/blob/master/v1/brokers/nats.go

I have created a repo with the entire code.  You are going to have to go through it to see how I did it.

There may be things missing compared to the AMPQ implementation as Nats may have things missing.

Anyway, this is the best that I can do.  I no longer use machinery, I have developed my own solution.

**Comment by Blogoslov** [comment]
> Anyway, this is the best that I can do. I no longer use machinery, I have developed my own solution.

Hello @paulm17 . Thanks for the sharing, I will review and check your solution. Thanks a lot.

By the way - does your new solution is available on github or some other place?

**Comment by paulm17** [comment]
@Blogoslov unfortunately it's not.  I really recommend looking at all the other job queue solutions out there and breaking down how they work and then building something that suits your own workflow.  It's essentially what I did.
