### ISSUE TITLE
Result backend required

### ISSUE THREAD

**Issue by tspecht** [RichardKnop/machinery#136]
Hey guys,

I'm trying to use machinery with AMQP as a broker and am not interested in collecting any of the results for now... However i seem to not being able to start a server without a result backend configured? Any idea?

```
var cnf = config.Config{
		Broker:             os.Getenv("TASK_BROKER_URL"),
		MaxWorkerInstances: 0,
		AMQP:               config.AMQPConfig{
		    Exchange:     "machinery_exchange",
		    ExchangeType: "direct",
		    BindingKey:   "machinery_task",
		  },
	}

	server, err := machinery.NewServer(&cnf)
```

**Comment by RichardKnop** [comment]
It should be possible to start the server without backend. This line should ignore any errors:

https://github.com/RichardKnop/machinery/blob/master/v1/server.go#L32

However most functions will return error without a backend as it is required for most functionality, e.g.:

https://github.com/RichardKnop/machinery/blob/master/v1/server.go#L121

You can try using:

```
ResultBackend: 'eager '
```

This will use `eager` in-memory backend which is used for testing purposes.
