### ISSUE TITLE
Resume failed workflow?

### ISSUE THREAD

**Issue by coli** [RichardKnop/machinery#141]
If one of the task in a workflow failed, can I retry it and resume the rest of the workflow?

**Comment by RichardKnop** [comment]
@coli Not right now. I would like to implement a retry functionality so you can specify how many times to retry a failed task before giving up. But that's not implemented yet.

**Comment by RichardKnop** [comment]
@coli I have implemented a very basic retry logic. Hopefully it helps with your problem: https://github.com/RichardKnop/machinery#retry-tasks
