### ISSUE TITLE
received 'i/o timeout' error

### ISSUE THREAD

**Issue by Blogoslov** [RichardKnop/machinery#143]
Hello. When I have multiple tasks sometimes I received such message:

Dial Backend: dial tcp 10.84.150.42:58060: i/o timeout

and my flow stops with panic error. 

Is it possible to set some redial functionality to avoid such issue?

**Comment by RichardKnop** [comment]
What backend are you using?

**Comment by Blogoslov** [comment]
I'm using AMQ as a broker and backend.
Yes, broker has redial functionality. But this message from backend procedure.
