### ISSUE TITLE
Set state pending error: MOVED 2912 172.31.3.148:6379

### ISSUE THREAD

**Issue by jsm** [RichardKnop/machinery#145]
Hey,

Great work on this library so far.
Having an issue when using an elasticache redis-cluster, since it does sharding and what not, the node you connect to might return a `MOVED` which is basically a redirect to the IP of the node you should actually be hitting.

**Comment by RichardKnop** [comment]
@jsm @tingxin The redis broker has not been tested extensively with clusters. If any of you want to fix this issue (maybe improve the reds broker, perhaps there is better library for redistribution clusters), please raise a PR.

I will probably not have time in near to midterm future to spend time debugging and fixing this so it would be best if people using Redis broker contributed fix for this :)
