### ISSUE TITLE
Any way of passing arguments from worker to task?

### ISSUE THREAD

**Issue by clstb** [RichardKnop/machinery#146]
Hello,

I would like to use machinery to query a 3rd party REST api distributed via tasks. Best practice afaik would be to pass the api client from a worker process to the task routine. That way connections get used efficiently and caching integrated in the client would work flawless without creating a new client for every task.

Is there any way I can achieve this or something similar with machinery and if not do you consider adding a functionality that serves the issue?

**Comment by RichardKnop** [comment]
There is a built in support for passing context as first argument to tasks: https://github.com/RichardKnop/machinery/blob/master/v1/tasks/task.go#L21

Possibly something similar could be done to optionally inject other objects to the task. I would need to think of some way to make this generic though so you can pass arbitrary object which might not be straightforward.

You could have all your tasks import a package which stores http client internally and reuse the same client that way?

Something like this:

```go
package mytasks

import "github.com/clstb/project/shared"

func SomeTask() error {
    client := shared.Client

    // or something similar?
}
```

**Comment by RichardKnop** [comment]
@clstb what do you think?

**Comment by clstb** [comment]
Storing the API client internally appears to be the best solution. I forgot that this was actually a thing. I could probably do the same thing with a DB connection too.

I´m a beginner in terms of microservices so there is another question you could help me out with. 

The API I query returns simple JSON. Do you think I should go for the approach you advised in https://github.com/RichardKnop/machinery/issues/70 and store everything in a external DB right away or only my processed data?

I feel like since there already is a ResultBackend it should be used and pass the result back serialized. So I dont have to create a table for every endpoint I query.

**Comment by clstb** [comment]
I think we can close this by now. I figured that using MongoDB as ResultBackend and general persistent storage is the most convinient way to handle data for my application.
