### ISSUE TITLE
Need example for non-block run

### ISSUE THREAD

**Issue by Blogoslov** [RichardKnop/machinery#147]
Hello,
could you please share an example how to use non block tasks run?

As example I used 'machinery.NewGroup' and added tasks into group, then I used 'server.SendGroup' and sent tasks for execution and then I did block execution which stopped and wait when tasks will be generated

```
for _, asyncResult := range asyncResults {
			result, err := asyncResult.Get()
			if err != nil {
				log.Error("RunMachineryTasks: ", err)
			}
			log.Debug(" completed asyncResult")
			log.Debug(result.Interface())
		}
```

How can I start tasks and continue get information that some tasks from the mentioned above group are completed just to be able insert other portions of tasks into this group and do not wait when all group will be completed?

(P.S. I know that you can say me that I should send all number of tasks to the group and no necessary to separate it, but on my side I every time receive error message that too many open files and I have to separate group by portions and it works well, but I don't want to wait when group will be completed and send another portions of tasks on fly)

Thanks a lot.

**Comment by Blogoslov** [comment]
Any help?

**Comment by RichardKnop** [comment]
That is not possible right now. Not sure how to achieve that in efficient way in a distributed system like this (which runs on multiple servers).

In the `README` file it is mentioned that `asyncResult.Get()` is something which you shouldn't really do in your code. It's mostly for testing purposes but you should design your tasks to be asynchronous so you would never need to get a result of a task in blocking way with `asyncResult.Get()`.

**Comment by Blogoslov** [comment]
Sorry, but your comment very confuses me. You say that asyncResult.Get() is not recommended for usage (it is only for testing) but how on my program I will know that tasks are completed? 
For instance - in my program, I started all necessary servers (Postgres, RabbitMQ, Redis and others), started my flow tasks and send to server.SendGroup all my thousand tasks. These tasks are working and require for example half day for completion. After it completed, my program should stop all servers (Postgres, RabbitMQ, Redis and others). How to know when I need to start my last procedure to shut down servers. Of course, this task can't be a part of server.SendTask' procedure because it will not be completed because of servers will be down.
So how I should proceed in this case?

P.S. By the way - all your examples have this instruction to use block way to get results after tasks completion and no any non-block tasks run. Is it possible to see examples with the non-block run?

Thanks in advance!
