### ISSUE TITLE
Is machinery ready for production?

### ISSUE THREAD

**Issue by ishail** [RichardKnop/machinery#15]
Hi @RichardKnop , I'm moving from python to golang and I need a celery like architecture to handle asynchronous tasks for almost real time execution. Machinery looks a great fit for it, but I would like to get your honest review about whether it is ready to use in production and how much time it will take?

**Comment by RichardKnop** [comment]
My honest opinion is it is not ready for production environment. I have not yet used it on any production server and I would probably not recommend it.

I have been quite busy with work couple of last weeks/months so I haven't worked on the codebase that much. It would help if somebody else contributed as well which would help move this project towards production readiness sooner.

There are two priorities I'd say. Sorting out dependencies via vendoring (maybe something like godep?), and finishing chords (a group of parallel tasks with a callback).

Richard

**Comment by ishail** [comment]
Thanks. First let me analyze the architecture then I would love to contribute on this.

**Comment by RichardKnop** [comment]
@ishail I have spend some serious time finishing the remaining priorities. Chords are now supported, dependencies are managed with godep. Also fixed couple of bugs. It's definitely closer to production ready now :)
