### ISSUE TITLE
Multi Config file only create same Config object

### ISSUE THREAD

**Issue by saggit** [RichardKnop/machinery#151]
If i have multi config file(config.yml), v1/config/file.go:14 will stop create new Config object after the first config file loaded. I am not sure it's done by purpose or a bug, But if i want to have multi server, I need put multi conf, 

btw, comment 
`// if configLoaded {
 // 	return cnf
// }` works fine

-----------------------------------------
edit: the comments above does not help.

-------------------
edit:
comment above and here: //Refresh(newCnf) and return newCnf seems solve the problem.

**Comment by RichardKnop** [comment]
Have you set `keepReloading` to true? That needs to be set to true for auto config refresh to work.

**Comment by saggit** [comment]
I don't want the reload feature, what I need is create multi Config object with different settings

**Comment by baiyunping333** [comment]
```go
import(
...
"gopkg.in/yaml.v2"
"github.com/RichardKnop/machinery/v1/config"
"github.com/RichardKnop/machinery/v1/log"
...
)

func NewFromYaml(cnfPath string) *config.Config {
    var newCnf *config.Config = &config.Config{}

    data, err := config.ReadFromFile(cnfPath)
    if err != nil {
        log.FATAL.Printf("File not exists, %s", err)
    }

    if err := yaml.Unmarshal(data, newCnf); err != nil {
        log.FATAL.Printf("Unmarshal YAML error: %s", err)
    }

    return newCnf
}
```

in the way:
```go
cnf = NewFromYaml(*configPath)
```
may help.

**Comment by baiyunping333** [comment]
keepReloading is chicken ribs！

**Comment by RichardKnop** [comment]
I'm open to PRs to refactor the config. I agree it's a bit sketchy at the moment.

**Comment by RichardKnop** [comment]
@saggit @baiyunping333 I have refactored config. Now it should work better. Let me know if it's good enough.
