### ISSUE TITLE
Support for SQS and S3 results backend

### ISSUE THREAD

**Issue by mbyio** [RichardKnop/machinery#152]
Sorry if this is annoying - I did see #117 - but I thought we ought to have an open issue/feature request since I would like to be able to use SQS.

**Comment by RichardKnop** [comment]
Sure there can be an open issue. I am not planning to add support for these new backends myself though so it would need to be contributed by somebody else.

There still needs to be more focus on making current broker/backend implementations more robust.

**Comment by codepushr** [comment]
@michael-younkin If you are still interested have a look at this fork https://github.com/udacity/machinery/tree/babcock/sqs_broker

They already implemented SQS, however no idea how robust/tested it is.

**Comment by michael-younkin** [comment]
Nice! I wish I had seen this sooner.

Unfortunately, we needed something a little more robust, and so far we don't need all the features provided by machinery, so we ended up writing our own little framework. We might have time to revisit it in a few months though!

**Comment by KirinDave** [comment]
@michael-younkin @codepushr We're using it in production. Right now we only support fifo queues but we're about to add non-fifo (as we've discovered that we actually don't care about the fifo nature for the jobs we run at all). 

We've also got a port in Typescript that we're gonna open source Real Soon Now(tm)
