### ISSUE TITLE
OnSuccess callback receives only last result from returned arguments from the previous task

### ISSUE THREAD

**Issue by StTymur** [RichardKnop/machinery#155]
https://github.com/RichardKnop/machinery/blob/master/v1/worker.go#L163
```
        // Trigger success callbacks
	for _, successTask := range signature.OnSuccess {
		if signature.Immutable == false {
			// Pass results of the task to success callbacks
			args := make([]tasks.Arg, 0)
			for _, taskResult := range taskResults {
				args = append([]tasks.Arg{{
					Type:  taskResult.Type,
					Value: taskResult.Value,
				}}, successTask.Args...)
			}
			successTask.Args = args
		}

		worker.server.SendTask(successTask)
	}
```
This snippet is from worker.go . It seems that the inner cycle doesn't work as supposed. At the end of the day it appends only last argument from `taskResults` to `successTask.Args`. If it is intended behavior (though it doesn't seem to), than there is no need for cycle. 
This way, we can't pass 2 or more results from the task to the next task in chain
Thank you!

**Comment by RichardKnop** [comment]
If the task is immutable then not results from previous task should be passed.

If immutable is set to false then all results from previous task should be prepended (not appended) to input arguments of the callback task.

So if it only prepends the last argument, that's a bug. Maybe it should be like this?

```go
			// Pass results of the task to success callbacks
                        args := make([]tasks.Arg, len(taskResults))
			for i, taskResult := range taskResults {
                                args[i] = tasks.Arg{
					Type:  taskResult.Type,
					Value: taskResult.Value,
				}
			}
			successTask.Args = append(args, successTask.Args...)
```

It makes more sense to prepend the results to the argument list of the callback task, no? So add them to the beginning of the list of arguments the callback task will receive.

That seems more natural to me like and I think most people would expect such behavior.

So I think that's the reason that inner cycle was constructed in such way.

What do you think?

I'm not sure when I will have enough time to take a look at this and run some tests. So if you want to fix this yourself, feel free to submit a PR.

**Comment by StTymur** [comment]
I'm sorry, I meant 'prepended' in my first comment. Yes, sure, the intended behaviour explained in the docs is the most natural one. It's just a little bug, that makes onSuccess callback to prepend only last argument. I think I could make a PR, some time soon. However, if someone used this exact behavior (relied on getting only last result as an argument) this would lead to breaking compatibility which would not be compile-time recognizable. What do you think about this?

Thanks for answer!

**Comment by RichardKnop** [comment]
I think making a breaking change now should still be possible even though not ideal. This library is fairly new and I would hope most people are pinning a specific commit when they use it in their projects.

Once I start doing proper releases (so from release v1.0.0) no breaking changes should be introduced. I think this project is getting close to thinking about making an official `1.0.0` release as it has been in development for quite a while and lately there haven't been any big changes really, mostly just refactoring and better testing.

**Comment by StTymur** [comment]
Great! 
I submitted PR for this!
https://github.com/RichardKnop/machinery/pull/156
