### ISSUE TITLE
Argument count of remaining task in chain changes after completion

### ISSUE THREAD

**Issue by codepushr** [RichardKnop/machinery#158]
Hey Richard,

thanks for this package. I'm encountering a strange behaviour. Not sure if I'm just misunderstanding anything on a fundamental level or if this is a weird bug.

When building a `Chain` of let's say 2 tasks the underlying JSON message looks correct, but after the first task is finished the new message with the remaining task has changed. More specifically the argument count changed.

- Using Redis & Redis for broker and storage
- The same setup works perfectly using `Group`

My code:
```go
s1 := tasks.Signature{
    Name: "saveAsImg",
    Args: []tasks.Arg{
        {
            Type:  "string",
            Value: "~/Desktop/sample.pdf",
        },
    },
}
s2 := tasks.Signature{
    Name: "report",
    Args: []tasks.Arg{
        {
            Type:  "string",
            Value: "~/Desktop/sample.kfpx",
        },
        {
            Type:  "string",
            Value: "~/Desktop/sample.pdf",
        },
    },
}
chain := tasks.NewChain(&s1, &s2)
_, err := mq.SendChain(chain)
```

Which produces the following message with the 1. task having exactly 1 argument and the 2. task having 2 arguments.
```json
{"UUID":"task_49427355-ae83-4107-8b8e-114c7ff8201b","Name":"saveAsImg","RoutingKey":"","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Type":"string","Value":"~/Desktop/sample.pdf"}],"Headers":null,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":[{"UUID":"task_57941b88-b8dd-49e8-964d-2b65ecc3c0f7","Name":"report","RoutingKey":"","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Type":"string","Value":"~/Desktop/sample.kfpx"},{"Type":"string","Value":"~/Desktop/sample.pdf"}],"Headers":null,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null}],"OnError":null,"ChordCallback":null}
```
Now the first task gets processed error free and the second one in `OnSuccess` gets triggered:
```
{"UUID":"task_57941b88-b8dd-49e8-964d-2b65ecc3c0f7","Name":"report","RoutingKey":"","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Type":"int","Value":0},{"Type":"","Value":null},{"Type":"","Value":null},{"Type":"string","Value":"~/Desktop/sample.kfpx"},{"Type":"string","Value":"~/Desktop/sample.pdf"}],"Headers":null,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null}
```
As you can see we now have 5 arguments for our 2. task - of which the first 3 are nonsense, only the last 2 are our predefined arguments.

Which leads to the following error message:
`ERROR: 2017/08/04 22:15:07 worker.go:257 Failed processing task_57941b88-b8dd-49e8-964d-2b65ecc3c0f7. Error = Reflect task args error:  is not one of supported types`

due to the malicious new argument `{"Type":"","Value":null}`.

Any hints?

**Comment by RichardKnop** [comment]
By default, the chain passes results of each task to its callback. So in this case I assume what's happening is that your first task returns 3 results (plus error) which get prepended to the second task that is defined as a success callback.

You can disable this behavior by making a task immutable. Try this:

```go
s2.Immutable = true
```

This is described in the README file if you look here:

https://github.com/RichardKnop/machinery#chains

But also here:

https://github.com/RichardKnop/machinery#signatures

(the `Immutable` attribute description)

In essence, let's say you chained these tasks:

1. add(1, 1)
2. add(5, 5)
3. multiple(4)

Default behavior would be: 

```
multiply(add(add(1, 1), 5, 5), 4)
```

Or written differently:

```
((1 + 1) + (5 + 5)) * 4 = 12 * 4 = 48
```

Just set `Immutable` to true for each task where you don't want to pass in results from previous task in the chain.

**Comment by codepushr** [comment]
Wonderful, so it's a feature. Sorry for missing this. I had to set `s1` instead of `s2` to immutable for the error to resolve though.

Thanks a bunch!

**Comment by codepushr** [comment]
**Appendix**
Maybe it's only me but it might be more intuitive to append previous results into a separate field. For me the `args` field should always be immutable as it sort of reflects the initial arguments.

**Comment by RichardKnop** [comment]
That's a good idea. It would perhaps be better under a separate field.
