### ISSUE TITLE
Support for task scheduling

### ISSUE THREAD

**Issue by rvolykh** [RichardKnop/machinery#160]
### Problem
Need to add possibility to execute tasks according to the given schedule (mostly presented by Cron)
e.g: 
1. Exact time task
```
 Start task "x1" at 2018/08/14   
```
\*  It can be solved even now by ETA field

2. Reoccurring task
```
 Start task "x2" every Monday at 8AM
```
Or even more complicated
```
 Start task "x3" every Friday at 8PM starting from 2018/01/01 and finishing at 2018/12/31
```

### Attempt
https://github.com/rvolykh/machinery/pull/1/files (work in progress).
Have few problems related to several instances of broker (sender)

_____
What do you think about possibility to add such feature? Maybe your view on it, or ways how it can be acquired, etc.

Thanks

**Comment by maxpowel** [comment]
At this moment I'm calculating the next execution at the end of the task:
eta := time.Now().UTC().Add(time.Second * 5)
signature.ETA = &eta
And then send this task to the server. I need to define a package variable with a reference to the machinery server instance so I can use it inside of the task for send tasks inside a task.

You should control onError and onSuccess events, imagine that your task raises an error and you dont enqueue your task, you should use onError to know this (in my case I have a dynamic scheduling, depending to the result the task will be re executed in a few seconds or in hours, like google crawler)

**Comment by rvolykh** [comment]
Wow, thanks, very interesting idea
