### ISSUE TITLE
what is 'max_worker_instances' option in example YAML file?

### ISSUE THREAD

**Issue by Blogoslov** [RichardKnop/machinery#165]
Hello,

what does mean 'max_worker_instances' option in example YAML configuration file? What it for?
I did not find in the code where it uses.

Regards.

**Comment by RichardKnop** [comment]
@Blogoslov I have removed that. It used to be an option to limit number of tasks a single worker can process at a time.

It was moved to a specific worker attribute. See here: https://github.com/RichardKnop/machinery/pull/159
