### ISSUE TITLE
Is it possible on OnSuccess callback assign Chain or Group tasks?

### ISSUE THREAD

**Issue by Blogoslov** [RichardKnop/machinery#166]
Hello,
my flow has different branches which are separated - tasks, chain, groups.  Is it possible that after single Task complete I  need submit multiple parallel tasks using sendGroup function but using OnSuccess callback in Signature structure? Now I see that it accept only single tasks ( []*Signatures)

Thanks in advance.

**Comment by Blogoslov** [comment]
As I understood from the code it is not possible at this moment and complex flow steps are not allowing.

@RichardKnop, do you plan to support complex flow steps in near future? I'm ready to help you in this way because this is really important things.

Best regards.

**Comment by Blogoslov** [comment]
Richard, 
How do you think is it reasonable to have such feature that OnError and OnSuccess callbacks can support a different kind of tasks (group, chain, single and etc)?

And how do you think is it possible to do in current code implementation just make several changes? I'm ready to support this enhancement.

Thanks in advance.

**Comment by RichardKnop** [comment]
@Blogoslov Sorry for late reply. I think it would be possible to do this but it would require couple of changes to how success callbacks work now. If you are ready to support this feature feel free to submit a PR.
