### ISSUE TITLE
'tasks_xxx' not deleted from RabbitMQ queues

### ISSUE THREAD

**Issue by Blogoslov** [RichardKnop/machinery#167]
Hello Richard,
I use AMQP as a broker and result backend. 
In one of the previous 'machinery' versions, I saw that when the task is completed then results were deleted from AMQP and queue was everytime empty. But now I see that it grows with every my tasks execution and I see multiple result tasks like 'task_030a87b7-1b69-4638-becc-a2965d0712fe' are in the queue and they are not deleted. 

Could you please advise is it expected behavior or not? Or I miss some new option which says do not delete them.

Best regards!

**Comment by RichardKnop** [comment]
I don't recommend using AMQP as backend but if you must, the last commit I just added will ensure the task state queues will get deleted automatically after 1 hour.

**Comment by Blogoslov** [comment]
Richard, does it means that if my task which is in PEND mode will not be processed by workers (the reason can be too little number of workers or too heavy tasks which take too much time for processing) then it will be deleted from the queue? Or you are speaking about only about completed tasks?

Best regards!

**Comment by RichardKnop** [comment]
@Blogoslov No. The tasks are being stored in a separate queue (by default called `machinery_tasks` but this can be changed by `DefaultQueue` setting). However task states are stored in task specific queues (there is no other way to do this with RabbitMQ unfortunately, therefor I recommend AMQP/Memcache or AMQP/Redis combo). These expire after 1 hour but this can also be changed via `ResultsExpireIn` setting.
