### ISSUE TITLE
Add array and map support to argument types

### ISSUE THREAD

**Issue by hamidfzm** [RichardKnop/machinery#169]
These array and map types are native json serializable in Go. Please add support for these args:
```go
[]string
[]int
[]int64
map[string]int
map[string]string
map[int]string
...
```

**Comment by mymtw** [comment]
@RichardKnop what to if I need to pass map[string]string into my function, which will be called by signature?

**Comment by RichardKnop** [comment]
@hamidfzm Adding slices here: https://github.com/RichardKnop/machinery/pull/240
