### ISSUE TITLE
Question: 'prefetch_count' and 'concurency'

### ISSUE THREAD

**Issue by Blogoslov** [RichardKnop/machinery#170]
I have a question - how mentioned above options are correlated with each other?

for example a set 
`server.NewWorker("machinery_worker", 0)`
which means from doc  'makes the number of concurrently executed tasks unlimited'

But in config I have following option

`  prefetch_count: 1`

which means for AMQP that each worker will receive only 1 task from the queue.

I have 3 workers (as example). I submitted 11 tasks in parallel and I see that with mentioned options all tasks distributed on 3 workers at the same time (4 tasks on 1 worker, 4 tasks on 2 worker and 3 tasks on 3 worker). How it possible if 'prefetch_count=1' and each worker should run only 1 task?

If I change `server.NewWorker("machinery_worker", 1)` then it works as expected, but I don't understand why we need 'prefetch_count' option if it does not affect on workers?

**Comment by RichardKnop** [comment]
The `prefetch_count` is different to concurrency setting (the second parameter to `server.NewWorker`). In your case you'd want to do:

```go
server.NewWorker("machinery_worker", 1)
```

Prefetch count is a RabbitMQ specific thing, see here for explanation: https://www.rabbitmq.com/consumer-prefetch.html

**Comment by mymtw** [comment]
@RichardKnop is it means that better to set `concurrency setting`(the second parameter to server.NewWorker) always equals to `prefetch_count`?
