### ISSUE TITLE
can't send tasks to worker

### ISSUE THREAD

**Issue by MaJiangBo** [RichardKnop/machinery#171]
use example demo send tasks to worker ,can't get result.that's task state always "PENDING".I use redis do it

var cnf = &config.Config{
	Broker:             "redis://localhost:6379",
	DefaultQueue:       "machinery_tasks",
	ResultBackend:      "redis://localhost:6379",
	AMQP:               &config.AMQPConfig{
		Exchange:     "machinery_exchange",
		ExchangeType: "direct",
		BindingKey:   "machinery_task",
		PrefetchCount: 1,
	},
}

**Comment by MaJiangBo** [comment]
use example demo send tasks to worker ,can't get result.that's task state always "PENDING"

**Comment by deanchou** [comment]
Good job.
I'm following up too.

**Comment by j-xu3** [comment]
This is because you have AMQP settings in config, this will cause the worker search `AMQP.bindingKey` instead of `defaultQueue`.  task object could not be found, That's the reason why it is always in `pending` state.

**Comment by zhex** [comment]
This is because you have AMQP settings in config, this will cause the worker search AMQP.bindingKey instead of defaultQueue. task object could not be found, That's the reason why it is always in pending state.

**Comment by MaJiangBo** [comment]
thanks very much

**Comment by RichardKnop** [comment]
Sorry for late reply. As @zhex has said you have AMQP settings in the config so it is trying to connect to RabbitMQ. Remove the AMQP part of config if you are using Redis and it should work.
