### ISSUE TITLE
Wrong pool logic in SendGroup

### ISSUE THREAD

**Issue by vidmed** [RichardKnop/machinery#172]
Hello.
Here is logic of pool in SendGroup() method
https://github.com/RichardKnop/machinery/blob/master/v1/server.go#L186

You initialize pool with only one element:
https://github.com/RichardKnop/machinery/blob/master/v1/server.go#L188
and then you work only with one element:
https://github.com/RichardKnop/machinery/blob/master/v1/server.go#L194
https://github.com/RichardKnop/machinery/blob/master/v1/server.go#L207

So all tasks are sending synchronously - this is a wrong behavior.

Also if sendConcurrency==0 - we will block forever.

**Comment by RichardKnop** [comment]
@vidmed Thanks for finding this bug. I have made a quick PR to fix it: https://github.com/RichardKnop/machinery/pull/173

If you want to review it, please feel free to do so.

**Comment by vidmed** [comment]
Yeah, that`s ok. Thank you.
