### ISSUE TITLE
Custom Recovery Handling

### ISSUE THREAD

**Issue by jsm** [RichardKnop/machinery#178]
Right now, task execution recovery is handled by printing the stack trace.

It would be great to be able to initialize a worker with a function that takes the error, as a sort of custom recovery handler.

In my case, I might want to capture the error and send it to our error tracking service.

**Comment by RichardKnop** [comment]
Yes, the current logic for recovering from panics is here: 

https://github.com/RichardKnop/machinery/blob/master/v1/tasks/task.go#L54-L68

It would need to be made customizable which it currently isn't. It might not be too difficult to add this functionality.

**Comment by jsm** [comment]
I think this PR provides a way to custom handle panics, since panics are wrapped in errors and sent up the stack.

https://github.com/RichardKnop/machinery/pull/238

**Comment by jsm** [comment]
This has been implemented in https://github.com/RichardKnop/machinery/pull/238
