### ISSUE TITLE
ResultBackend Overhead

### ISSUE THREAD

**Issue by clstb** [RichardKnop/machinery#179]
There is a very big overhead when running huge quantity groups. (8000+ tasks per group)
This is probably caused by inefficient task state monitoring (IO with the ResultBackend) since redis takes like a whole core when running the tasks. My example worker takes up the other 3 cores. Also the worker crashes sometimes when receiving to many messages.
This was tested with nearly no-op tasks (increment and print) and Redis/MongoDB as ResultBackend. I dont have the example code anymore but it was very simple so the description should be enough to rebuild it.

**Comment by RichardKnop** [comment]
@clstb I haven't done much performance testing so it is quite possible there is some low hanging fruit how to increase performance and reduce the overhead. It would require more time to investigate and research than I have right now though.

**Comment by gngeorgiev** [comment]
@clstb if you are still using machinery, maybe this PR might help with the performance - https://github.com/RichardKnop/machinery/pull/406

**Comment by clstb** [comment]
Thanks for your effort on this.
I'm not using machinery anymore but fixing this issue will improve machinery nevertheless.



Best regards,
Claas
