### ISSUE TITLE
Sidekiq

### ISSUE THREAD

**Issue by spinx** [RichardKnop/machinery#18]
Hey, 

just a suggestion - use Sidekiq way of doing things to make this useful for a lot broader user base. Will help with adoption/migration for sure since a lot of people are using that.  

I can document everything (how sidekiq works with redis) and also help with some implementation, although my Go skills leave a lot to be desired ;)

**Comment by RichardKnop** [comment]
Hey,

I am not very familiar with Sidekiq. If you can help me document how it works that would be great. Getting this useful for a broader user base is something I would like to do. Also getting other people help would be great as so far this has been a one man project.

Don't worry about your Go skills. I am a generalist myself although Go has been really growing on me recently.

**Comment by mirzac** [comment]
Hello... 
there is already a project that implements workers and jobs in Go that are compatible with Sidekiq: 
https://github.com/jrallison/go-workers

**Comment by spinx** [comment]
@mirzac 
I'm aware of go-workers, but I was drawn to this solution because of groups, chords and chains as well.

@RichardKnop OK, great. I'll start with the docs and some code next week. What are you using as a backend now ? Do you think that Memcache make sense as a queue ?

**Comment by RichardKnop** [comment]
@spinx Using memcache as a queue is probably a bad idea. I recommend RabbitMQ as a top choice followed by Redis. There is also disque which is interesting but I haven't added adapter for that yet.

**Comment by spinx** [comment]
@RichardKnop Yeah I had backends folder open and was a bit perplexed why memcache would be used as a queue. I saw later these are results backends :)
