### ISSUE TITLE
Question: what means option 'sendConcurrency' in Sendroup function

### ISSUE THREAD

**Issue by Blogoslov** [RichardKnop/machinery#180]
Hello,

I see that this is a new option (it was not available at least before release v1.0). Also in the examples on your 'readme' page you did not use this parameter. Could you please write brief explanation what is this and which values should it contain and what they will mean?

`SendGroup(group *tasks.Group, sendConcurrency int)`

Thanks in advance.

**Comment by RichardKnop** [comment]
It is a concurrency setting to be used when sending group tasks to the broker. Previously they were sent in a for loop but now you can specify how many to send at the same time in goroutines.
