### ISSUE TITLE
Support for scheduled tasks

### ISSUE THREAD

**Issue by blalor** [RichardKnop/machinery#19]
I'd love to see some kind of scheduled task support, where you can submit a task for execution at a point of time in the future.

**Comment by RichardKnop** [comment]
@blalor This is definitely on my TODO list.

**Comment by balzaczyy** [comment]
My practice is to use a cron library (like "github.com/robfig/cron") and feed task event accordingly. E.g.,

````go
c := cron.New()
for _, v := range conf.CronJobs {
	if parts := strings.SplitN(v, " ", 2); len(parts) == 2 {
		cmd, spec := parts[0], parts[1]
		c.AddFunc(spec, func() {
			server.SendTask(&signatures.TaskSignature{
				UUID: genJobId(cmd),
				Name: cmd,
			})
		})
	}
}
c.Start()

**Comment by RichardKnop** [comment]
Something like celery monitor would be ideal. I will eventually get around to do that. But lot of other things that have higher priority right now.
