### ISSUE TITLE
AdjustRoutingKey error with redis

### ISSUE THREAD

**Issue by yang-f** [RichardKnop/machinery#190]
This is my config.yml

```

broker: 'redis://127.0.0.1:6379'
default_queue: 'yangf_test'
result_backend: 'redis://127.0.0.1:6379'
results_expire_in: 3600000
```

and run worker

```
INFO: 2017/10/13 18:33:26 redis.go:82 queue:yangf_test
INFO: 2017/10/13 18:33:27 redis.go:82 queue:yangf_test
INFO: 2017/10/13 18:33:28 redis.go:82 queue:yangf_test
INFO: 2017/10/13 18:33:29 redis.go:82 queue:yangf_test
INFO: 2017/10/13 18:33:30 redis.go:82 queue:yangf_test
INFO: 2017/10/13 18:33:31 redis.go:82 queue:yangf_test
INFO: 2017/10/13 18:33:32 redis.go:82 queue:yangf_test
INFO: 2017/10/13 18:33:33 redis.go:82 queue:yangf_test
INFO: 2017/10/13 18:33:34 redis.go:82 queue:yangf_test
INFO: 2017/10/13 18:33:35 redis.go:82 queue:yangf_test
```

It's normal now...

But  when i run send with same config file
```

INFO: 2017/10/13 18:35:34 redis.go:146 signature.RoutingKey:
WARNING: 2017/10/13 18:35:34 broker.go:59 b.cnf.AMQP:&{machinery_exchange direct map[] machinery_task 3}.
INFO: 2017/10/13 18:35:34 redis.go:149 signature.RoutingKey:machinery_task
```

I have no AMQP config in config.yml  at all. The cnf.AMQP should be nil but no.
And the task always send to queue 'machinery_task'.
I think it's a bug.......

**Comment by RichardKnop** [comment]
How are you loading the config from file? I mean where do you specify path to `config.yml`?

**Comment by zyanho** [comment]
redis could not use task, all delay task shoud send to delayed_tasks, if there 2+ queue worker
then all worker should got block, the delay task could not handle by the right worker
#149

**Comment by RichardKnop** [comment]
@zyanho @yang-f This could be caused by: https://github.com/RichardKnop/machinery/pull/204

Once I merge into master try it again and hopefully it works.
