### ISSUE TITLE
Worker receives foreign tasks

### ISSUE THREAD

**Issue by rooty123** [RichardKnop/machinery#192]
After upgrading to latest version(from old 1 year version) I've noticed that workers that share same configuration receive tasks which they are not responsible for. The broker is Redis
```
Broker:        "redis://redis:6379,
ResultBackend: "redis://redis:6379",
DefaultQueue:  "machinery_tasks",
```
What am I doing wrong?

**Comment by RichardKnop** [comment]
Hard to tell. How do you configure workers. Maybe they have same tasks registered.

This test should verify workers only consume registered tasks: https://github.com/RichardKnop/machinery/blob/master/integration-tests/worker_only_consumes_registered_tasks_test.go#L133

**Comment by rooty123** [comment]
Turned out this happens  when there are no workers responsible for the task available.

**Comment by RichardKnop** [comment]
Even if all workers share the same queue but have different tasks registered, if task is not registered and worker receives it, the task should not be processed and re-queued instead. As seen here: 

https://github.com/RichardKnop/machinery/blob/master/v1/brokers/redis.go#L253

So not sure why that would happen. More robust way is to use different queues for different types of tasks / workers though so I suggest to configure different workers and then publish tasks using routing keys.

**Comment by rooty123** [comment]
Looks like it is not processed but printed out in console, that's why it looks like it take foreign task. Sorry for misunderstanding.
