### ISSUE TITLE
Wait For All Tasks To Finish On Shutdown

### ISSUE THREAD

**Issue by makkalot** [RichardKnop/machinery#194]
Hi,

Would you be interested in MR when SIGTERM is received to wait for all of the tasks to finish before exiting? We have very sensitive tasks that shouldn't be interrupted or at least should be given a chance to finish.

I'm thinking of a setting on machinery like `waitTasks bool` and `waitTaskTimeout time.Duration` where the behavior will be : 
- if not set continue with current behavior
- if set should wait for the tasks for the timeout period to give them a chance before exiting and if timeout just exit. 

Opinions ?

**Comment by RichardKnop** [comment]
Yes this sounds like a good idea. Basically when you quit a worker this method is being called (it's implemented slightly differently for different brokers):

https://github.com/RichardKnop/machinery/blob/master/v1/brokers/interfaces.go#L12

So we will need to configure it to wait for running tasks to finish or at least wait some time period.

**Comment by RichardKnop** [comment]
Just looking at AMQP implementation and it seems that should already wait for tasks to complete when it receives interrupt signal. Take a look here:

https://github.com/RichardKnop/machinery/blob/master/v1/brokers/amqp.go#L165

The wait group's `Wait` method is deferred to run before returning from the function.

Every task which is started will increment the wait group's count by 1: https://github.com/RichardKnop/machinery/blob/master/v1/brokers/amqp.go#L179

And again decrement the wait group once task is processed: https://github.com/RichardKnop/machinery/blob/master/v1/brokers/amqp.go#L184

So when interrupt signal is received it should trigger the stop channel:

**Comment by RichardKnop** [comment]
I have just ran a simple test with long running task and it seems current implementation doesn't work. So it needs to be fixed.

**Comment by RichardKnop** [comment]
@makkalot I submitted a PR for this: https://github.com/RichardKnop/machinery/pull/195

**Comment by makkalot** [comment]
That was quick @RichardKnop, thanks giving it a try :)
