### ISSUE TITLE
how to use different queues in different tasks

### ISSUE THREAD

**Issue by takfate** [RichardKnop/machinery#196]
RT

**Comment by RichardKnop** [comment]
You can configure which queue the task will be routed to by adjusting `RoutingKey` parameter of a signature: https://github.com/RichardKnop/machinery/blob/master/v1/tasks/signature.go#L23

By default, when you don't specify a custom routing key, the task will be routed to default queue, see here: https://github.com/RichardKnop/machinery/blob/master/v1/brokers/broker.go#L51

If you are using AMQP, there are more options for routing as well, you can also play with different types of exchanges like direct, fanout, topic etc.

**Comment by takfate** [comment]
thanks, i would know whether the worker could be registered by an object 's function

**Comment by zyanho** [comment]
machinery could not handle different task with retry
if use redis, RoutingKey not work, because redis only have one default key for delay task name "delayed_tasks"

**Comment by zyanho** [comment]
#149

**Comment by RichardKnop** [comment]
@zyanho Should be fixed in the new release.
