### ISSUE TITLE
how to make some workers run  in the background

### ISSUE THREAD

**Issue by takfate** [RichardKnop/machinery#198]
Launch a worker will block the process
Should I execute `go worker.launch()`?

**Comment by RichardKnop** [comment]
Yes, currently you would use goroutine. Perhaps we could add an alternative launch method which will take error channel as input. This would be non blocking and you can then handle the worker process yourself via the error channel.

**Comment by RichardKnop** [comment]
@takfate What about:

```go
func (worker *Worker) LaunchAsync(errorsChan chan error)
```

See here: https://github.com/RichardKnop/machinery/pull/199
