### ISSUE TITLE
sendGroup is very slow when task number is large

### ISSUE THREAD

**Issue by balzaczyy** [RichardKnop/machinery#20]
I tried to use send group task feature. However, it turns out to be quite slow. The scheduling frequency seems to be fixed. So I end up using send task one by one.

What is exact the benefit to use send group instead of sending task one by one?

**Comment by RichardKnop** [comment]
It shouldn't be slow. I will have to test it over the weekend. All SendGroup does is:

1. Sets state of all tasks in a group to pending.
2. Sends all tasks to the broker.

Both steps can actually be parallelised with goroutines I guess. I will need to look at where the bottleneck is.

The group is just a wrapper used to send multiple tasks at once (plus also used by chords).

What broker and backend are you using?

**Comment by balzaczyy** [comment]
I'm using rabbitmq for broker and wrote a elasticsearch backend to keep all the job status, which all host in a private cloud. There is one lead task, which scans 10K records, and update each record in a single task. After this initial setup, the following delta update may be far less.

On a second thought, maybe I should try rabbitmq in local. I will have another test today.

**Comment by balzaczyy** [comment]
Using a local broker improves a lot. This should work for now.

**Comment by balzaczyy** [comment]
Still one question. What's the exact benefit to use a group, instead of sending task one by one? Is there any design consideration?

**Comment by RichardKnop** [comment]
After I merged the last PR, SendGroup should send tasks in parallel using goroutines. Should be faster now.
