### ISSUE TITLE
Is there a pattern for dealing with redis master/slave configuration?

### ISSUE THREAD

**Issue by alexhudici** [RichardKnop/machinery#200]
If redis is set up to have a master and several fall back nodes, is there a built in way to deal with redis master election in case of a failure on one node or is there a pattern for changing the URL for workers? 
Do servers have to be recreated with `NewServer()` and workers have to be re-registered or would it be enough to change the `ResultBackend` and `Broker` variables in the configuration of a running server?

**Comment by RichardKnop** [comment]
@alexhudici For Redis I am using this library https://github.com/go-redsync/redsync/tree/v1.0.1 for connection pooling. This should work well for master / fall back nodes. When master nodes doesn't work, workers should retry to connect to one of fall back nodes. I have not tested this setup though so cannot confirm for sure it works correctly.

Changing variables in the configuration should be enough in theory. However remember that a worker subscribes to a queue and starts consuming from it (it's a long running process) so you'd need to restart it.

**Comment by alexhudici** [comment]
Thats awesome thank you @RichardKnop. I will have a look at the library and for the workers, I figured I would have to create a new machinery server and register new workers to it since the server is where the redis IP gets registered. Unless it is safe to switch the IP of the existing server struct and just restart it since the queue would have the same name.

**Comment by RainbowMango** [comment]
@alexhudici Have you tested master-slave scenario?  Does worker retry to slave when master doesn't work?
