### ISSUE TITLE
how to send task just by redis 

### ISSUE THREAD

**Issue by jzhbiao** [RichardKnop/machinery#201]
I use redis as  broker , and I want to send task just like "rpush machinery_tasks ******", but this show error
.what is the right format in ******, because is very convenient to use,help me.

**Comment by jzhbiao** [comment]
I want to send task just use redis command  in redis, then machinery listen it , is that a proper way?

**Comment by jzhbiao** [comment]
I try to rpush like this:
127.0.0.1:6379> rpush machinery_tasks "[123 34 85 85 73 68 34 58 34 116 97 115 107
 95 51 55 101 57 101 48 55 57 45 100 99 57 101 45 52 55 48 101 45 56 98 51 100 4
5 56 50 102 101 50 101 48 99 99 56 101 57 34 44 34 78 97 109 101 34 58 34 99 97
108 95 110 117 114 101 114 121 95 100 97 116 97 34 44 34 82 111 117 116 105 110
103 75 101 121 34 58 34 34 44 34 69 84 65 34 58 110 117 108 108 44 34 71 114 111
 117 112 85 85 73 68 34 58 34 34 44 34 71 114 111 117 112 84 97 115 107 67 111 1
17 110 116 34 58 48 44 34 65 114 103 115 34 58 110 117 108 108 44 34 72 101 97 1
00 101 114 115 34 58 110 117 108 108 44 34 73 109 109 117 116 97 98 108 101 34 5
8 102 97 108 115 101 44 34 82 101 116 114 121 67 111 117 110 116 34 58 48 44 34
82 101 116 114 121 84 105 109 101 111 117 116 34 58 48 44 34 79 110 83 117 99 99
 101 115 115 34 58 110 117 108 108 44 34 79 110 69 114 114 111 114 34 58 110 117
 108 108 44 34 67 104 111 114 100 67 97 108 108 98 97 99 107 34 58 110 117 108 1
08 125]"
and it show: WARNING: 2017/11/28 10:17:38 worker.go:60 ****: json: cannot unma
rshal number into Go value of type tasks.Signature

**Comment by RichardKnop** [comment]
@jzhbiao This should work:

```
rpush machinery_tasks '{"UUID":"task_1158d38e-2afb-4fbe-a08f-9e1b11e6bfa3","Name":"add","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Type":"int64","Value":1},{"Type":"int64","Value":1}],"Headers":null,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null}'
```

**Comment by jzhbiao** [comment]
thank you for reply, and I try it but also error : 
(error) WRONGTYPE Operation against a key holding the wrong kind of value,
it seems '"' is not a right format to rpush, and i will google it ,or whether you can show me why I wrong.
127.0.0.1:6379> rpush machinery_tasks '{"UUID":"task_1158d38e-2afb-4fbe-a08f-9e1
b11e6bfa3","Name":"add","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"",
"GroupTaskCount":0,"Args":[{"Type":"int64","Value":1},{"Type":"int64","Value":1}
],"Headers":null,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":n
ull,"OnError":null,"ChordCallback":null}'
(error) WRONGTYPE Operation against a key holding the wrong kind of value
127.0.0.1:6379> rpush machinery_tasks "{'UUID':'task_1158d38e-2afb-4fbe-a08f-9e1
b11e6bfa3','Name':'add','RoutingKey':'machinery_task','ETA':null,'GroupUUID':'',
'GroupTaskCount':0,'Args':[{'Type':'int64','Value':1},{'Type':'int64','Value':1}
],'Headers':null,'Immutable':false,'RetryCount':0,'RetryTimeout':0,'OnSuccess':n
ull,'OnError':null,'ChordCallback':null}"
(error) WRONGTYPE Operation against a key holding the wrong kind of value
127.0.0.1:6379> rpush machinery_tasks "{\"UUID\":\"task_1158d38e-2afb-4fbe-a08f-
9e1b11e6bfa3\",\"Name\":\"add\",\"RoutingKey\":\"machinery_task\",\"ETA\":null,\
"GroupUUID\":\"\",\"GroupTaskCount\":0,\"Args\":[{\"Type\":\"int64\",\"Value\":1
},{\"Type\":\"int64\",\"Value\":1}],\"Headers\":null,\"Immutable\":false,\"Retry
Count\":0,\"RetryTimeout\":0,\"OnSuccess\":null,\"OnError\":null,\"ChordCallback
\":null}"
(error) WRONGTYPE Operation against a key holding the wrong kind of value

**Comment by jzhbiao** [comment]
thank you for reply
