### ISSUE TITLE
Stuck on "Waiting for running tasks to finish before shutting down"

### ISSUE THREAD

**Issue by mavidser** [RichardKnop/machinery#206]
Hi. I'm not really sure what I'm doing wrong.

Some details:
I'm using redis as the broker. Earlier, I tried a blank ResultBackend, which resulted in tasks not being executed. I later added a ResultBackend anyway (the same as the broker), and the tasks being executed. But whenever I try to gracefully exit out of the worker (SIGINT), this is what happens:
```
^CWARNING: 2017/12/05 19:05:44 worker.go:75 Signal received: interrupt                                 │4 R  6221 22631 15701  0  80   0 -  7302 -      pts/12   00:00:00 ps
WARNING: 2017/12/05 19:05:44 worker.go:80 Waiting for running tasks to finish before shutting down     │0 S  6221 30546 31918  0  80   0 -  5078 wait_w pts/4    00:00:00 redis-cli
^CWARNING: 2017/12/05 19:05:45 worker.go:75 Signal received: interrupt                                 │0 S  6221 30638 25972  0  80   0 -  5282 poll_s pts/1    00:00:00 tmux
^C^C^C
```
It kinda stops acknowledging any further sigint with no sign of what running task it has to finish.

Any ideas what I might be doing wrong?
There are no long-running tasks here. This happens even if I register ` map[string]interface{}{}` as the tasks.

**Comment by RichardKnop** [comment]
Can you try with the latest release? I have fixed a bug with `AdjustRoutingKey`.

In previous release way to fix the bug you are experiencing would be to delete / comment out AMQP related settings from config file. So get rid of this subsection of config file:

```
amqp:
  binding_key: machinery_task
  exchange: machinery_exchange
  exchange_type: direct
  prefetch_count: 3
```

There was a bug when binding key from AMQP settings would be used also for Redis broker. That should be fixed now.

Let me know if you still have issue.

**Comment by mavidser** [comment]
Solved

**Comment by RichardKnop** [comment]
Glad to here.

Basically, this condition was being evaluated as true before even for Redis broker:

https://github.com/RichardKnop/machinery/blob/master/v1/brokers/broker.go#L100

Changing it so it works properly and is only applied for AMQP broker fixed the issue.

**Comment by mavidser** [comment]
Ah. I did face this issue earlier, but I proceeded with changing the config file to fix the issue, like you suggested earlier.

Though, this particular issue actually turned out to be #208
