### ISSUE TITLE
worker doesn't make use of concurrency

### ISSUE THREAD

**Issue by balzaczyy** [RichardKnop/machinery#22]
My task logic would send new tasks within a task body. In this case, this worker no longer receive no tasks until it finishes the current one. It can be workarounded by initiating multiple workers on one nodes but it seems strange.

To me, it's a waste of resource. But is it a valid scenario? Or should I avoid initiating tasks within the task body?

**Comment by RichardKnop** [comment]
Yes. This is something which needs to get fixed. Feel free to submit a PR if you think this is a low hanging fruit. I will take a look myself.

You should probably avoid publishing new tasks in the task body but still the worker needs to use concurrency properly without the need to launch multiple workers. One worker process should be capable of processing multiple tasks at the same time using goroutines.

**Comment by balzaczyy** [comment]
I managed to refine my task logic to make best use of concurrency and avoid running too long, e.g., split long task into smaller pieces. 

I also had a check on the above change. It looks quite promising. When will it be merged into the master branch?

**Comment by RichardKnop** [comment]
I need to fix a failing integration test.

Plus there is an issue with AMQP backend which I need to solve.

I might get some more free time this weekend.

**Comment by RichardKnop** [comment]
@balzaczyy Merged. Using AMQP as a result backend is a bit dodgy right now (I made it work with a clever hack but I would recommend to use Redis or Memcache as result backends if you can).
