### ISSUE TITLE
[Question] How use extended Logrus logger types?

### ISSUE THREAD

**Issue by Blogoslov** [RichardKnop/machinery#222]
Hello,
I have used Logrus logger as a custom logger in Machinery. How can I use other logger types like log.Info, log.Debug and etc which support Logrus?

At this moment only Println, Panic and Error type are supported

**Comment by Blogoslov** [comment]
any suggestions? or is this impossible?

**Comment by RichardKnop** [comment]
@Blogoslov The current logging implementation supports different log levels. See here:

https://github.com/RichardKnop/machinery/blob/master/v1/log/log.go

So you can define INFO, WARNING, ERROR, FATAL levels.

Basically you can define a custom logger for every level of logs by implementing this interface:

https://github.com/RichardKnop/logging/blob/master/interface.go#L5

Which is identical to native `log` interface of Golang's core library.

The only change that would be needed would be to allow passing custom logs per level here: https://github.com/RichardKnop/machinery/blob/master/v1/log/log.go#L21

This could be a small PR. Feel free to modify that file so you can have different loggers per log level.
