### ISSUE TITLE
Allow custom retry backoff

### ISSUE THREAD

**Issue by jmcarp** [RichardKnop/machinery#226]
It looks like the retry backoff function is hard-coded to use the fibonacci sequence. Users might want other backoff logic, like exponential, static, etc. WDYT about allowing a custom backoff function that accepts the retry index and returns a delay?

**Comment by RichardKnop** [comment]
@jmcarp This is a good idea. If you want to submit a PR, feel free. Sorry for ignoring bunch of issues and feature requests but time to work on machinery has been very limited last month or two. 

How do you propose to implement this, make the backoff function used for retrying a string argument of a task signature? And have couple of functions for different use cases? Or allow users to use custom backoff functions?

I wonder what would be an easy way to allow custom backoff functions as retries are handled in quite a simple manner now: https://github.com/RichardKnop/machinery/blob/master/v1/worker.go#L156

**Comment by jmcarp** [comment]
I think that registering a map of named retry functions and including the map key in the signature would work. We could also use an api more like celery's and allow users to return custom retry errors from a task that include a delay: `return NewRetry(5 * time.Second)`. WDYT?

**Comment by RichardKnop** [comment]
@jmcarp This is a Celery like solution which might be good enough for most use cases: https://github.com/RichardKnop/machinery/pull/250

What do you think?

**Comment by jmcarp** [comment]
Looks good. Thanks!
