### ISSUE TITLE
MongoDB backend - multiple chord triggering

### ISSUE THREAD

**Issue by ItsLeeOwen** [RichardKnop/machinery#232]
Chords are being triggered multiple times.

Fix - https://github.com/RichardKnop/machinery/pull/231

**Comment by ItsLeeOwen** [comment]
@RichardKnop  sorry was the issue report too poor?  I can outline standard expected behavior, actual result, steps to reproduce if that's helpful.

**Comment by RichardKnop** [comment]
I thought this was fixed already. It it's still an issue then this should be open.

If you can try to rebase your PR against master and make sure CI passes, then it would be possible to merge it.

**Comment by ItsLeeOwen** [comment]
Fix Merged https://github.com/RichardKnop/machinery/pull/247
