### ISSUE TITLE
uint64 in Signature receive different value when use reids

### ISSUE THREAD

**Issue by WingGao** [RichardKnop/machinery#251]
Create a signature with uint64 `185135722552891243 `
```go
sig := NewSignature("test", []Arg{
		{
			Type:  "uint64",
			Value:  uint64(185135722552891243),
		},
	})
msg, _ := json.Marshal(sig)
t.Log(string(msg))
```
The output result is:
```json
{"UUID":"task_d1432cc0-47ff-4eae-a930-0f9372dd6dff","Name":"test","RoutingKey":"","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Type":"uint64","Value":185135722552891243}],"Headers":null,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null}

```

Worker log:
```
redis.go:273 Received new message: {"UUID":"task_d1432cc0-47ff-4eae-a930-0f9372dd6dff","Name":"test","RoutingKey":"suchu_tasks","ETA":"2018-03-01T18:11:44.27456522+08:00","GroupUUID":"","GroupTaskCount":0,"Args":[{"Type":"uint64","Value":185135722552891230}],"Headers":null,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null}
```

They have the same signature, but uint64 value has been changed to `185135722552891230`

**Comment by WingGao** [comment]
I found these code https://github.com/RichardKnop/machinery/blob/master/v1/brokers/redis.go#L113-L116
And https://github.com/RichardKnop/machinery/blob/master/v1/brokers/redis.go#L258-L261
will shrink the uint64 value.

**Comment by RichardKnop** [comment]
@WingGao I think this is because JSON treats all numbers as floating point (it doesn’t have int or uint type). So the conversion from uint to float and then back to uint might be causing this. Can you verify that’s the case? Any suggested solutions?

**Comment by WingGao** [comment]
@RichardKnop You're right.
Here is the test.
```go
func TestNewSignature(t *testing.T) {
	var uint64Val uint64 = 185135722552891243
	sig := NewSignature("test", []Arg{
		{Type: "uint64", Value: uint64Val},
	})
	msg, _ := json.Marshal(sig)
	sig2 := &Signature{}
	json.Unmarshal(msg, sig2)
	sig2Val := sig2.Args[0].Value.(float64)
	t.Logf("%f", sig2Val)
	if uint64(sig2Val) != uint64Val {
		t.Errorf("uint64 value should be %d but get %f", uint64Val, sig2Val)
	}
}
```
It will convert to `float64`.
My current solution is  change the `uint64` to `string` in the my sender code.
I think it's not a universal method, but is the easiest.

**Comment by RichardKnop** [comment]
@WingGao Solution here: https://play.golang.org/p/MqOaajygFqp

**Comment by RichardKnop** [comment]
@WingGao Pull request here: https://github.com/RichardKnop/machinery/pull/252
