### ISSUE TITLE
Warning when using []string (or other slice types) as a return value

### ISSUE THREAD

**Issue by rakeshbala** [RichardKnop/machinery#254]
Worker prints out a warning when using `[]string` as a return value
For e.g when task is:
```
func Test(stra string) (res []string, err error) {
    res = []string{stra}
    return res, nil
}
```
And I send 
```
        testSig := tasks.Signature{
            Name: "test",
            Args: []tasks.Arg{
                {
                    Type:  "string",
                    Value: "test",
                },
            },
        }
```
I get this warning on the worker and prints the result as empty:
```
WARNING: 2018/03/01 11:18:45 worker.go:182 [test] is not []string
INFO: 2018/03/01 11:18:45 worker.go:186 Processed task task_a02e8872-3929-49f9-a94e-a199488b8a30. Results = []
```
However I am able to fetch the result using the `Get` method of the result.

**Comment by rakeshbala** [comment]
I think this is because:
https://github.com/RichardKnop/machinery/blob/master/v1/tasks/reflect.go#L152

value.([]interface{}) returns false for an `interface{}` type pointing to `[]string`
Here is a an example snippet https://play.golang.org/p/HqIvwMqRa4N

However, I haven't checked how it is working while retrieving the results.

**Comment by RichardKnop** [comment]
@rakeshbala Basically the error you see in the logs is coming from here: https://github.com/RichardKnop/machinery/blob/master/v1/worker.go#L204-L212

It does not affect functionality as it's just a debug log so task results are visible in the logs. But this is still a bug we should try to fix.

**Comment by RichardKnop** [comment]
@rakeshbala This has been fixed now: https://github.com/RichardKnop/machinery/pull/257
