### ISSUE TITLE
Pin go.uuid to commit on master?

### ISSUE THREAD

**Issue by F21** [RichardKnop/machinery#259]
There was a breaking change in go.uuid (after v1.2.0), where the interface of `uuid.NewV4()` was changed to return an error in addition to the uuid.

I've updated a lot of my projects to pin go.uuid to `36e9d2ebbde5e3f13ab2e25625fd453271d6522e` using dep as the dependencies I am using have updated to the new interface.

After the upgrade, I am facing a problem where machinery won't import using dep due to machinery pinning go.uuid to v1.2.0.

Would you be interested in upgrading machinery to `36e9d2ebbde5e3f13ab2e25625fd453271d6522e`? This would enable machinery to be used with projects using versions of go.uuid after the breaking change was introduced.

I am happy to make a PR for this.

**Comment by RichardKnop** [comment]
@F21 Yes, you can update the dependency and make a PR. Should be fairly small pull request.
