### ISSUE TITLE
AMPQ broker connection reusing

### ISSUE THREAD

**Issue by Requilence** [RichardKnop/machinery#26]
Is there a reason to open/close broker connection on every message publishing? 
In a single goroutine with AMPQ connection reusing I have 110 msg publish/sec vs 55 msg/sec with current implementation.
Also with using of goroutines to publish messages I was able to get 34000 msg/sec on the same configuration. Looks like goroutines is safe when reusing AMPQ connection

**Comment by RichardKnop** [comment]
@Requilence Hi Roman. There is no specific reason for it. You can submit a PR if you want. I'm a bit busy at the moment but performance improvements like this are needed.

**Comment by Requilence** [comment]
@RichardKnop Ok, I will test my solution and if everything works great I will create PR.

**Comment by wizard580** [comment]
@Requilence 
Can you show your solution? I'll try to test it.

**Comment by Requilence** [comment]
@wizard580 https://github.com/RichardKnop/machinery/pull/36

**Comment by mission-liao** [comment]
I've working on some go-amqp stuff (another worker queue project) and found this (issue)[https://github.com/streadway/amqp/issues/119] in that project. Quote from one discussant:

```
I personally saw massive performance improvements by using a channel per go routine. 
```

In current implementation of machinery, we create a channel (and connection) per 'SendTask', it seems a reasonable implementation, or maybe we would at least maintain a 'channel pool' for each request from different go routine.

**Comment by Requilence** [comment]
@mission-liao Also the similar approach is using in https://github.com/go-mgo/mgo. 
Initially I made the same decision (reusing connection, reinit channel) but doesn't see any performance benefits from thus. I will repeat tests today and come back with results

**Comment by RichardKnop** [comment]
Great work and investigation guys. It seems reusing channels might be the way to go.
