### ISSUE TITLE
ResultBackend is not optional

### ISSUE THREAD

**Issue by Requilence** [RichardKnop/machinery#27]
>Result backend to use for keeping task states and results. This setting is optional, you can run >Machinery without keeping track of task results.

But in fact when I try to leave ResultBackend empty there is a panic at
```
src/github.com/RichardKnop/machinery/v1/server.go:102 (0x2a4492)
	(*Server).SendTask: if err := server.backend.SetStatePending(signature); err != nil
```

**Comment by RichardKnop** [comment]
@Requilence This is a bug. Thanks, I'll take a look at it.

**Comment by RichardKnop** [comment]
@Requilence I made the result backend mandatory for now. Most workflow functionality requires a backend to store tasks states anyways.
