### ISSUE TITLE
SQS Broker has race condition where tasks could be lost

### ISSUE THREAD

**Issue by bmarini** [RichardKnop/machinery#275]
https://github.com/RichardKnop/machinery/blob/master/v1/brokers/aws_sqs.go#L209-L215

If the process dies after deleting but before processing a task, the task is lost.

It looks like it was an intentional decision to delete the message from the queue after receiving it, but before processing it. This is inconsistent with the AMQP implementation though, where the message is ack'd after processing:

https://github.com/RichardKnop/machinery/blob/master/v1/brokers/amqp.go#L237-L238

Is there a reason not to move the deletion until after the task is processed? As long as the visibility timeout is configured appropriately it should be fine I think

**Comment by RichardKnop** [comment]
@bmarini Hi. I have actually only written support for RabbitMQ and Redis brokers and for AMQP/Redis/Memcache backend. All other brokers and backends have been contributed so I am not overly familiar with the codebase.

I will need to look at the code in more detail once I have more time (perhaps this weekend). SQS support was contributed here https://github.com/RichardKnop/machinery/pull/212 by @mjetpax so perhaps you can give him a shout to get a faster answer :)

**Comment by bmarini** [comment]
Thanks for the info @RichardKnop that helps!

**Comment by RichardKnop** [comment]
@bmarini You can submit a PR to fix this if you want :)

**Comment by RichardKnop** [comment]
@bmarini I have merged a fix for this issue to the master branch.
