### ISSUE TITLE
panic: reflect: call of reflect.Value.Len on zero Value

### ISSUE THREAD

**Issue by siredwin** [RichardKnop/machinery#278]
There was a task that came in to the queue and failed internally without finishing or getting the result.
The production server could not start at all after that.
My only remedy was to issue this command

`sudo rabbitmqctl purge_queue machinery_tasks`

After that the server started right back up.

**I was able to recreate problem.**

`INFO: 2018/04/24 14:42:45 amqp.go:235 Received new message: {"UUID":"zipper_s3_6b8ec73c-123e-47b2-b6a2-aae6c94bf133","Name":"streams3","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Type":"string","Value":"edwin/zipped/zipped-5d659d94-f306-413c-81bc-3f728405e67e.zip"},{"Type":"[]string","Value":null},{"Type":"int64","Value":1},{"Type":"bool","Value":true}],"Headers":null,"Immutable":false,"RetryCount":2,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null}
panic: reflect: call of reflect.Value.Len on zero Value
goroutine 83 [running]:
reflect.Value.Len(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:1038 +0x19c
github.com/RichardKnop/machinery/v1/tasks.reflectValues(0xc420566578, 0x8, 0x0, 0x0, 0xdcf101, 0xc420591ab0, 0x198, 0x0, 0x0)
	/home/edwin/IdeaProjects/gowork/src/github.com/RichardKnop/machinery/v1/tasks/reflect.go:224 +0xc7f
github.com/RichardKnop/machinery/v1/tasks.ReflectValue(0xc420566578, 0x8, 0x0, 0x0, 0xdcf1c0, 0xc420591ab0, 0x198, 0x0, 0x0)
	/home/edwin/IdeaProjects/gowork/src/github.com/RichardKnop/machinery/v1/tasks/reflect.go:70 +0x5d
github.com/RichardKnop/machinery/v1/tasks.(*Task).ReflectArgs(0xc42008ce60, 0xc420424b00, 0x4, 0x4, 0x13, 0xc420452ff0)
	/home/edwin/IdeaProjects/gowork/src/github.com/RichardKnop/machinery/v1/tasks/task.go:148 +0xd7
github.com/RichardKnop/machinery/v1/tasks.New(0xe4c0e0, 0xc420010020, 0xc420424b00, 0x4, 0x4, 0x0, 0x0, 0xc420636800)
	/home/edwin/IdeaProjects/gowork/src/github.com/RichardKnop/machinery/v1/tasks/task.go:45 +0x16f
github.com/RichardKnop/machinery/v1.(*Worker).Process(0xc42000c040, 0xc4201883c0, 0x18, 0xc4205bcf40)
	/home/edwin/IdeaProjects/gowork/src/github.com/RichardKnop/machinery/v1/worker.go:122 +0x1d5
github.com/RichardKnop/machinery/v1/brokers.(*AMQPBroker).consumeOne(0xc4203346e0, 0x15298e0, 0xc420300a20, 0x0, 0xc420566500, 0x10, 0x0, 0x0, 0x2, 0x0, ...)
	/home/edwin/IdeaProjects/gowork/src/github.com/RichardKnop/machinery/v1/brokers/amqp.go:237 +0x473
github.com/RichardKnop/machinery/v1/brokers.(*AMQPBroker).consume.func2(0xc4203346e0, 0xc4202eaa00, 0x1520a60, 0xc42000c040, 0xc4203e03c0, 0x0, 0xc4203e0360)
	/home/edwin/IdeaProjects/gowork/src/github.com/RichardKnop/machinery/v1/brokers/amqp.go:189 +0x8f
created by github.com/RichardKnop/machinery/v1/brokers.(*AMQPBroker).consume
	/home/edwin/IdeaProjects/gowork/src/github.com/RichardKnop/machinery/v1/brokers/amqp.go:188 +0x133
Process finished with exit code 2`

**Is it possible to get something better than a panic and shutting down the whole program?**

**Comment by RichardKnop** [comment]
@siredwin Can you try with the latest master? I have made a change to treat `NULL` in case of slices as an empty slice. The panic was caused because it was expecting an empty array such as `[]` for the value. It makes sense to treat `NULL` as empty slice though.

**Comment by siredwin** [comment]
I won't be able to test it but I will take the fix. It only occurred in production but not development, and I don't want to break the code again.
The way you described it sounds like what was happening. If someone else comes across it, they can comment.
