### ISSUE TITLE
Passing in database connections to tasks?

### ISSUE THREAD

**Issue by paulm17** [RichardKnop/machinery#293]
Hi,

Coming from other solutions such as gocraft/work.  I'm able to pass the database connection via context to the code that is processed by the worker.

This ensures that only 1 long lived connection is being used, rather than multiple connections being opened and closed.

Is it possible to instantiate a db connection in the worker and then have it available to a task?

Can someone knock up an example.

Thanks

**Comment by regaw-leinad** [comment]
A quick example... I group the handlers in related structs, then create a new "handler" and pass the db context to its initialization function.  The worker can then access it's `db` field while executing.

For example:

```go
type TaskHandler struct {
	db *DB
}

func NewTaskHandler(db *DB) *TaskHandler {
	return &TaskHandler{db: db}
}

func (h *TaskHandler) DoThing1(a, b string) error {
	// Do stuff with database in here
	h.db.Query("...")
	return nil
}
```

**Comment by paulm17** [comment]
I'm sorry, but you haven't given me enough information.  I'm missing some crucial elements.

Let me explain what I have and hopefully you can point me to the right direction.

I have two "workers" in different programs.  The job worker and a "message queue" worker.

The job worker starts the machinery worker process:

	func startServer() (*machinery.Server, error) {
		cnf, err := loadConfig()
		if err != nil {
			return nil, err
		}

		// Create server instance
		server, err := machinery.NewServer(cnf)
		if err != nil {
			return nil, err
		}

		// Register tasks
		tasks := map[string]interface{}{
			"someTask": tasks.SomeTask,
		}

		return server, server.RegisterTasks(tasks)
	}

	func worker() error {
		consumerTag := "machinery_worker"

		cleanup, err := tracers.SetupTracer(consumerTag)
		if err != nil {
			log.FATAL.Fatalln("Unable to instantiate a tracer:", err)
		}
		defer cleanup()

		server, err := startServer()
		if err != nil {
			return err
		}

		// The second argument is a consumer tag
		// Ideally, each worker should have a unique tag (worker1, worker2 etc)
		worker := server.NewWorker(consumerTag, 0)

		return worker.Launch()
	}

The "message queue" worker is one which listens on a nats queue listening for messages, which originate from PHP.  It's the usual runTask from the example:

	func runTask(server *machinery.Server, event_name, event_data string) error {
		cleanup, err := tracers.SetupTracer("sender")
		if err != nil {
			log.FATAL.Fatalln("Unable to instantiate a tracer:", err)
		}
		defer cleanup()

		insertTask := tasks.Signature{
			Name: event_name,
			Args: []tasks.Arg{
				{
					Type:  "string",
					Value: event_data,
				},
			},
		}

		/*
		 * Lets start a span representing this run of the `send` command and
		 * set a batch id as baggage so it can travel all the way into
		 * the worker functions.
		 */
		span, ctx := opentracing.StartSpanFromContext(context.Background(), "send")
		defer span.Finish()

		batchUUID, err := uuid.NewV4()

		if err != nil {
			return fmt.Errorf("Error generating batch id: %s", err.Error())
		}

		batchID := batchUUID.String()
		span.SetBaggageItem("batch.id", batchID)
		span.LogFields(opentracing_log.String("batch.id", batchID))

		log.INFO.Println("Starting batch:", batchID)

		asyncResult, err := server.SendTaskWithContext(ctx, &insertTask)
		if err != nil {
			return fmt.Errorf("Could not send task: %s", err.Error())
		}

		results, err := asyncResult.Get(time.Duration(time.Millisecond * 5))
		if err != nil {
			return fmt.Errorf("Getting task result failed with error: %s", err.Error())
		}
		log.INFO.Printf("%v", tasks.HumanReadableResults(results))

		return nil
	}

What I want to do.  Is instantiate the database object inside the job worker.  Where it's only done once and then passed to the task.

Why do I want to do this?  I have well over 100 tasks (100 task.go files), all of which interact with the database.  Currently, I'm opening a new connection in each task execution.  For a task queue that is going to be processing millions to tens of millions of tasks.  This is going to be a problem.

**I've also seen issue #175 and I'm also not sure if passing in the db connection via the context is a good idea or not.  It would be nice, that when a worker starts.  It can pull in a db connection from machinery itself?**

Many thanks

**Comment by edwardmp** [comment]
@paulm17 Running into the same issue. Did you ever find a proper solution. If so, can you share it?

**Comment by paulm17** [comment]
Unfortunately I did not.  My work around was to build out my own message queue.  Drastic I know, but I couldn't find something open source which would satisfy all my requirements.  I'll release it when it's appropriate to do so.  But don't hold your breath.  👍

**Comment by vincenthcui** [comment]
We run into the same problem that how to manage mysql connections in machinery tasks.

There are two different ways to manage connections. One is opening a connection in the front of task, and close it in the end. It's easy to test since task is stateless and what the task returns only depends on what parameters we passed into it, but it's onerous, we have to passing the same connection information to every task, to make tasks know how to create connection.

The other one is maintains a global connection pool, task get one connection from pool when used and release it back when task finished. It's very easy to use, you just import and use it, but don't care where and how it comes. But it's very hard to test, since a task depends on global state. And in this situation, we need close the pool properly.

Does machinery aims to solve this situation? Or if you can introduce some "best practice" @RichardKnop

**Comment by marcocali** [comment]
@paulm17 and @edwardmp you can use _closure_ to share variables between tasks within the same worker. 

Here an example:

![Screen Shot 2019-12-12 at 12 45 06 pm](https://user-images.githubusercontent.com/1436181/70677522-87d10d80-1ce3-11ea-9948-5fc4cbbe0bd5.png)

![Screen Shot 2019-12-12 at 12 45 59 pm](https://user-images.githubusercontent.com/1436181/70677531-8d2e5800-1ce3-11ea-95cf-64b28fe7f4db.png)

**Comment by marcocali** [comment]
Full example here: https://github.com/marcocali/machinery/blob/master/example/machinery.go

**Comment by marcocali** [comment]
@RichardKnop please close this issue.
