### ISSUE TITLE
Can we separate brokers and backends into their own packages?

### ISSUE THREAD

**Issue by WillAbides** [RichardKnop/machinery#298]
It would be useful to put each broker and backend in its own project.  For example `.../v1/backends/redis` and `.../v1/brokers/amqp`.  This would reduce the binary size and number of dependencies for projects that use just one broker and backend.  I tried this out for a project I'm working on now, and eliminating all but the redis broker and backend reduced our binary size by 7MB and removed six projects from our Gopkg.lock and vendor<sup>1</sup>.

I did a little exploratory work on splitting the backends into separate packages<sup>2</sup>, and I didn't run into any obstacles.  The refactor was actually a bit easier than I expected.

Is this a change that would be considered?  I realize this is a breaking change that will require some thought and probably a v2.

In the mean time we will be using a [redis-only branch](https://github.com/WillAbides/machinery/tree/redisonly) to meet our project's immediate needs, but we look forward to using the upstream code again.

<sup>1</sup> Just removing the projects is significant for us because we need to account for licenses of all the code we distribute even if it isn't ever executed.

<sup>2</sup> https://github.com/WillAbides/machinery/compare/41d81167d33d6399bb54087fa64510799dca3e74...splitbackends

**Comment by RichardKnop** [comment]
@WillAbides This should be possible without breaking any backwards compatibility. I have made a quick PR and it seems to work: https://github.com/RichardKnop/machinery/pull/299

Regarding v2, that is quite a slow process and I'd probably rethink some design choices and rewrite internals from scratch. However given lack of time to invest in this, it might be few years before that happens. For now v1 remains what I mostly work on when I get some time.

**Comment by RichardKnop** [comment]
Done

**Comment by WillAbides** [comment]
Thanks for doing this so quickly.  I was taking a strict interpretation of backward compatibility since the methods like `NewRedisBackend` are exported, but if they aren't used outside the machinery in practice, then it isn't really a backward compatibility problem.

**Comment by RichardKnop** [comment]
I think most people are using factory functions and those didn't need to change.
