### ISSUE TITLE
Chord Callback Called Multiple Time

### ISSUE THREAD

**Issue by RichardKnop** [RichardKnop/machinery#30]
Chord callback is being called N times where N is number of tasks in the group.

This affects Redis and Memcache backends. AMQP backend is not affected.

Workaround until this is fixed is to make sure chord callback is idempotent.

**Comment by vamsu** [comment]
FYI, this affects mongo backend as well.

**Comment by RichardKnop** [comment]
@vamsu Update. This has been fixed for Redis backend now. The way to fix it is using distributed locks.

For MongoDB backend, you could fix this bug by implementing this method: https://github.com/RichardKnop/machinery/blob/master/v1/backends/mongodb.go#L100

See Redis implementation for reference: https://github.com/RichardKnop/machinery/blob/master/v1/backends/redis.go#L98
