### ISSUE TITLE
Is there a way to limit number of concurrent tasks

### ISSUE THREAD

**Issue by jaipradeesh** [RichardKnop/machinery#301]
Hello,

If I would like to limit a worker to process only n tasks at any given point of time, is there a way to configure it?

**Comment by Blogoslov** [comment]
I think you are asking about this parameter:

worker := server.NewWorker("worker_name", **10**)

**Comment by RichardKnop** [comment]
@jaipradeesh @Blogoslov That's correct. The second parameter to `server.NewWorker` is max number of concurrent tasks being processed by this worker at a time.
