### ISSUE TITLE
worker stopped process task after a while

### ISSUE THREAD

**Issue by balzaczyy** [RichardKnop/machinery#31]
I haven't nail down the root cause yet. But my worker seems to stopped working after it received a new message, and leave the message un-acknowledged. I tried purge the queue, and 3 were left un-acknowledged. Then I shutdown the worker, the 3 messages are changed back to ready.

I'm always use the latest code base and it has happened two times. Will try again to see if there is a pattern.

**Comment by RichardKnop** [comment]
Ok. Let me know if you find the cause of the problem or a way to reproduce it.

This is quite an early stage project so I expect there to be some issues and it will take some time to make it more robust.

**Comment by balzaczyy** [comment]
In Worker.Launch() loop, if retry is true, the returned error is eaten. I suspect there is some error and keep retrying won't auto-fix it. I have added a debug message to retry. It feels like time related.

Will update later.

**Comment by RichardKnop** [comment]
Ok. Seems promising.

I'm on a vacation now so I'll be online a bit less frequently over next couple of weeks.

Let me know when you find the culprit though.

**Comment by RichardKnop** [comment]
Found out anything?

**Comment by balzaczyy** [comment]
Sorry for the late response. I'm currently traveling. And yes, I did found the root cause. It's caused by my local change that disabled the worker task concurrency. And the exiting error channel is blocking the main loop. After I changed the error channel to non-blocking, the issue is gone. It can be closed now. 

发自我的 iPad
