### ISSUE TITLE
queue status and monitoring

### ISSUE THREAD

**Issue by alext234** [RichardKnop/machinery#327]
Is there any way for monitoring/checking statuses of the queues at the moment? Either exposed via http server or API to collect statistics.

**Comment by RichardKnop** [comment]
@alext234 Depends on your broker. There is a `GetState` method that can in theory be used: https://github.com/RichardKnop/machinery/blob/master/v1/backends/iface/interfaces.go#L22

However that won't work with AMQP broker right now. It would be ideal to create HTTP or RPC JSON API to expose task state. I am open to pull requests on this.
