### ISSUE TITLE
Dependency error when running machinary example

### ISSUE THREAD

**Issue by bharat-p** [RichardKnop/machinery#329]
Running into following error when trying to run sample machinery program in a package using new Go modules.

Here is the error:

```
vendor/github.com/garyburd/redigo/redis/pool.go:28:2: use of internal package connectors/vendor/github.com/gomodule/redigo/internal not allowed
```
Looks like its coming  from https://github.com/RichardKnop/redsync and I see that a recent commit was made there to take care of similar issue with `dep`. 

I believe to make it work with Go modules we need to tag master of (https://github.com/RichardKnop/redsync)  with v1.0.2 so that it can be pulled in by vgo when pulling machinery instead of current highest tag 1.0.1 which doesn't contain the fix

**Comment by chawco** [comment]
I'm also running into this issue -- @RichardKnop any chance we could get a v1.0.2 tag on your fork fo redsync to address this?
