### ISSUE TITLE
remove the checking for "https://sqs.." for SQS

### ISSUE THREAD

**Issue by alext234** [RichardKnop/machinery#332]
Is it possible to remove or to modify this checking at this line
https://github.com/RichardKnop/machinery/blob/master/v1/factories.go#L67

The reason is:

- I am testing with a local mock setup of SQS (using docker)
- I don't have `https`, just `http`
- My URL may not start with `sqs`

**Comment by bharat-p** [comment]
Maybe we disable this check when a special environment variable e.g. `DISABLE_STRICT_SQS_CHECK` is set? @RichardKnop  if you are ok, i can create a PR for this change

**Comment by alext234** [comment]
Yes,  why not. Thank you.
