### ISSUE TITLE
Remote execution of a task

### ISSUE THREAD

**Issue by jaipradeesh** [RichardKnop/machinery#336]
Hello there,

What if the task does something remotely? How to handle the status of the remote task a serial workflow.

Example:
- Assume a chain workflow. Task `foo` and task `bar` should in series (`bar` runs after `foo` is completed)
- Task `foo` triggers a build remotely
- When the remote build is completed, a message is pushed to a loopback RabbitMQ exchange
- On reception of the message from the remote task, task `bar` should be triggered

How to achieve the same with machinery? I see asyncResult but that's asynchronous within application's context.

Thanks.

**Comment by RichardKnop** [comment]
You can achieve this by chaining tasks `foo` and `bar`. Should be quite straightforward.
