### ISSUE TITLE
amqp problems

### ISSUE THREAD

**Issue by wizard580** [RichardKnop/machinery#34]
Work with amqp not stable:
from time to time sender hangs on results.Get()
fix: ctrl+c and re-run again. some times from 3rd try. 

Today I see worker crashed with this output:
/home/user/go/bin/src/github.com/RichardKnop/machinery/v1/brokers/amqp.go:161 +0x1c9

goroutine 13329 [select]:
github.com/RichardKnop/machinery/Godeps/_workspace/src/github.com/streadway/amqp.(*Connection).heartbeater(0xc820076240, 0x2540be400, 0xc8200e6300)
        /home/user/go/bin/src/github.com/RichardKnop/machinery/Godeps/_workspace/src/github.com/streadway/amqp/connection.go:494 +0x505
created by github.com/RichardKnop/machinery/Godeps/_workspace/src/github.com/streadway/amqp.(*Connection).openTune
        /home/user/go/bin/src/github.com/RichardKnop/machinery/Godeps/_workspace/src/github.com/streadway/amqp/connection.go:713 +0x805

goroutine 13330 [chan receive]:
github.com/RichardKnop/machinery/Godeps/_workspace/src/github.com/streadway/amqp.bufferDeliveries(0xc8200e65a0, 0xc8200e6540)
        /home/user/go/bin/src/github.com/RichardKnop/machinery/Godeps/_workspace/src/github.com/streadway/amqp/consumers.go:38 +0x7b
created by github.com/RichardKnop/machinery/Godeps/_workspace/src/github.com/streadway/amqp.(*consumers).add
        /home/user/go/bin/src/github.com/RichardKnop/machinery/Godeps/_workspace/src/github.com/streadway/amqp/consumers.go:74 +0x10b

goroutine 13372 [runnable]:
github.com/RichardKnop/machinery/Godeps/_workspace/src/github.com/streadway/amqp.(*Connection).heartbeater(0xc82391f320, 0x2540be400, 0xc8239754a0)
        /home/user/go/bin/src/github.com/RichardKnop/machinery/Godeps/_workspace/src/github.com/streadway/amqp/connection.go:494 +0x505
created by github.com/RichardKnop/machinery/Godeps/_workspace/src/github.com/streadway/amqp.(*Connection).openTune
        /home/user/go/bin/src/github.com/RichardKnop/machinery/Godeps/_workspace/src/github.com/streadway/amqp/connection.go:713 +0x805

goroutine 13371 [runnable]:
net.runtime_pollWait(0x7fb9dba4ab98, 0x72, 0xc820010180)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc823934610, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc823934610, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8239345b0, 0xc82393b000, 0x1000, 0x1000, 0x0, 0x7fb9dba45050, 0xc820010180)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820028628, 0xc82393b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc823975440)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc823975440, 0xc82393d2d0, 0x7, 0x7, 0x1, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7fb9dba4aef8, 0xc823975440, 0xc82393d2d0, 0x7, 0x7, 0x7, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:298 +0xe6
io.ReadFull(0x7fb9dba4aef8, 0xc823975440, 0xc82393d2d0, 0x7, 0x7, 0x1, 0x0, 0x0)
        /usr/local/go/src/io/io.go:316 +0x62
github.com/RichardKnop/machinery/Godeps/_workspace/src/github.com/streadway/amqp.(*reader).ReadFrame(0xc821d99ee0, 0x0, 0x0, 0x0, 0x0)
        /home/user/go/bin/src/github.com/RichardKnop/machinery/Godeps/_workspace/src/github.com/streadway/amqp/read.go:49 +0xbd
github.com/RichardKnop/machinery/Godeps/_workspace/src/github.com/streadway/amqp.(*Connection).reader(0xc82391f320, 0x7fb9dba4ae60, 0xc820028628)
        /home/user/go/bin/src/github.com/RichardKnop/machinery/Godeps/_workspace/src/github.com/streadway/amqp/connection.go:464 +0x172
created by github.com/RichardKnop/machinery/Godeps/_workspace/src/github.com/streadway/amqp.Open
        /home/user/go/bin/src/github.com/RichardKnop/machinery/Godeps/_workspace/src/github.com/streadway/amqp/connection.go:220 +0x3e3

amqp, server and workers are on the same server.

**Comment by wizard580** [comment]
In my little investigation I see there no amqp problems, but more general issues as this issue reproducable with redis too.

Situation:
I have 2 workers, all running in parallel on the same server. One worker registered only 1 task "worker1_task" and second only 1 "worker2_task". 
SendGroup -> result.Get() hangs.

Please test such case.

**Comment by wizard580** [comment]
May be look at this:
"consumeOne()"  calls  "taskProcessor.Process()", then workers "Process()" calls:
        task, err := worker.server.GetRegisteredTask(signature.Name)
	if err != nil {
		return err
	}
if task was not for this worker, Process() will return "err" and then will be "errorsChan <- err" at consumeOne(). So task discarded, sender/server will hang forever.
I think in case of failed "GetRegisteredTask" this task should be returned to queue, or better not fetched from queue (if this possible)

**Comment by wizard580** [comment]
For me it was fixed:
v1/worker.go
----
func (worker *Worker) Process(signature *signatures.TaskSignature) error {
   task, err := worker.server.GetRegisteredTask(signature.Name)
   if err != nil {
      worker.server.GetBroker().Publish(signature)
      return err
   }

**Comment by wizard580** [comment]
Is it acceptable or there will be released proper fix?

**Comment by RichardKnop** [comment]
@wizard580 This is acceptable. Can you create a PR?

**Comment by RichardKnop** [comment]
There will probably be a proper fix when I come back from the vacation.
