### ISSUE TITLE
Fetch task state by UUID

### ISSUE THREAD

**Issue by herpiko** [RichardKnop/machinery#340]
Is there any way to get the state of a task by UUID from a server instance? 

Assume that there are two instance of servers are up. We send a task with manually assigned UUID on the signature from server 1. Then we want to fetch the state of task by this UUID in the server 2.

In the examples, the only way to get the states is from asyncResult which derived from Send* functions. This asyncResult is only exists in the server where the tasks are sent from.

**Comment by herpiko** [comment]
Solved.

```
	chain, _ := tasks.NewChain(&buildSignature, &repoSignature)
	_, err = server.SendChain(chain) // the ChainAsyncResult are not used
	if err != nil {
		fmt.Println("Could not create server : " + err.Error())
	}

	// Recreate the AsyncResult instance using the signature and server.backend
	car := result.NewAsyncResult(&buildSignature, server.GetBackend())
	taskState := car.GetState()
	fmt.Printf("Current state of %v task is:\n", taskState.TaskUUID)
	fmt.Println(taskState.State)
```

**Comment by RichardKnop** [comment]
@herpiko correct, you can recreate async result on a different server and fetch task data that way. Perhaps it might be a good idea to add some helper functions for this to the server.

**Comment by samuelololol** [comment]
Any updates?

**Comment by Shahriar-Sazid** [comment]
> Solved.
> 
> ```
> 	chain, _ := tasks.NewChain(&buildSignature, &repoSignature)
> 	_, err = server.SendChain(chain) // the ChainAsyncResult are not used
> 	if err != nil {
> 		fmt.Println("Could not create server : " + err.Error())
> 	}
> 
> 	// Recreate the AsyncResult instance using the signature and server.backend
> 	car := result.NewAsyncResult(&buildSignature, server.GetBackend())
> 	taskState := car.GetState()
> 	fmt.Printf("Current state of %v task is:\n", taskState.TaskUUID)
> 	fmt.Println(taskState.State)
> ```
This works fine. But one important thing is, **setting UUID in task signature before sending task**. Without that this will not work properly.
