### ISSUE TITLE
Help inquiry

### ISSUE THREAD

**Issue by AlbinOS** [RichardKnop/machinery#341]
Hi,

I'm analysing different possibilities to use/implement a persistent queue in Go. My first though was Machinery/Redis but I'm afraid that the queue might grow quick big (several GBs) before being emptied and I was afraid of having all of this in-memory.

I was thinking on using BoltDB as job backend to ensure persistence, reliability and the possibility for the queue to grow quite big without issue.

Any take on this ? Thanks a lot !

**Comment by RichardKnop** [comment]
Nothing is stopping you from implementing your own result backend based on the interface provided: https://github.com/RichardKnop/machinery/blob/master/v1/backends/iface/interfaces.go#L8

I am trying to limit number of broker and backend implementations in this repository as it's becoming more difficult to maintain with every new addition.
