### ISSUE TITLE
GetPendingTasks does not return tasks having ETA

### ISSUE THREAD

**Issue by feelinc** [RichardKnop/machinery#342]
Hi,

I'm using version 1.4.4 with Redis for Broker and Backend. Unable to get pending tasks created having ETA.

I've tried not running the worker and send some tasks having ETA.

I'm using SendTaskWithContext, where I'm using the same background context for each task created.

When I'm not using ETA, and using the same background context, GetPendingTasks able to collect all tasks not yet consumed by worker.

Not sure if it's a bug or designed to working like that.

**Comment by RichardKnop** [comment]
Tasks with ETA for Redis are stored in a different queue, if you read the code. It's not a bug really but `GetPendingTasks` could be improved to also fetch data from the tasks that have ETA.

**Comment by feelinc** [comment]
I have check the `v1/brokers/redis/redis.go` source code. The tasks stored in "delayed_tasks".

The tasks added by "ZADD" command, but the `GetPendingTasks` is using "LRANGE" command, so redis will return error "WRONGTYPE Operation against a key holding the wrong kind of value", which result empty.
