### ISSUE TITLE
Worker doest exit if broker address is not reachable

### ISSUE THREAD

**Issue by eldadvcita** [RichardKnop/machinery#346]
Hi,
I tried to run my application with an invalid Backend address (AMQP). When I tired closing the app (CTRL+C) it stoped consuming but the application didn't exit.

The reason is that common.Broker.StopConsuming()` sending a message to stopChan:
```
// StopConsuming is a common part of StopConsuming
func (b *Broker) StopConsuming() {
	// Do not retry from now on
	b.retry = false
	// Stop the retry closure earlier
	select {
	case b.retryStopChan <- 1:
		log.WARNING.Print("Stopping retry closure.")
	default:
	}
	// Notifying the stop channel stops consuming of messages
	b.stopChan <- 1 // THIS LINE!
}
```
But there is no consumer for it. therefore we keep waiting forever. The consumer for this channel start listening only once we established connection (e.g. https://github.com/RichardKnop/machinery/blob/master/v1/brokers/amqp/amqp.go#L78).

To solve this issue, I suggest to change the `common.Broker.StopConsuming()` method into:
```
func (b *Broker) StopConsuming() {
	// Do not retry from now on
	b.retry = false
	// Stop the retry closure earlier
	select {
	case b.retryStopChan <- 1:
		log.WARNING.Print("Stopping retry closure.")
	default:
	}
	
	// It won't 
	// Notifying the stop channel stops consuming of messages
	select {
	case b.stopChan <- 1:
		log.WARNING.Print("Stop channel")
	default:
	}
}
```
or make the `stopChan` type of buffer channel (2), but it will make the code harder to read.

WDYT?

**Comment by RichardKnop** [comment]
@eldadvcita Sounds good

**Comment by F21** [comment]
I upgraded to 1.5.0 and noticed a bunch of `Stop channel` warning messages in my logs. Is there a reason why `Stop channel` is classed as a warning?
