### ISSUE TITLE
cannot find package "github.com/RichardKnop/machinery/v1/errors" after installing package using "go get"

### ISSUE THREAD

**Issue by toutouastro** [RichardKnop/machinery#354]

**Comment by toutouastro** [comment]
Following this article: http://masnun.rocks/2016/11/01/distributed-task-processing-in-golang/
The code does not run showing the above error!
I think the article should be updated (because the folder errors is already removed maybe it existed in a past version)!

**Comment by eldad87** [comment]
There is no such thing as `github.com/RichardKnop/machinery/v1/errors`, errors can be find in `github.com/RichardKnop/machinery/v1/tasks`
