### ISSUE TITLE
Concurrency for send group not working properly.

### ISSUE THREAD

**Issue by risav1994** [RichardKnop/machinery#355]
Hi,
    If the concurrency is set to 0 in server.SendGroup() then it works as suggested, but when you set it to, let's say 1, then it is still functioning as the one with 0. Can you explain the exact meaning of concurrency there?

**Comment by eldad87** [comment]
This variable define the goroutine pool size, in turn, this pool is used to send your tasks to the broker.
0 means unlimited, in order words the pool size will be equal to the amount of tasks you're about to send.

Value of 0 will send your messages the fastest (probably), 1 will keep the messages in order etc.
