### ISSUE TITLE
Add tasks in a chord from two different processes

### ISSUE THREAD

**Issue by risav1994** [RichardKnop/machinery#356]
Lets say there are 5 tasks to be processed in a group and 6th task is to be processed after success of 5 tasks. Now the 5 tasks are to be provided at different time and from different functions. How to do that using chord feature of machinery?

Function A => task 1 at 0 sec 
Function B => task 2  at 5 sec
Function C => task 3, 4 and 5 at 10 sec
Function D => task 6 
Task 1 shall start processing as arrived and so on.
How to use a chord here?

**Comment by eldad87** [comment]
Did you tried the `Signature.ETA`?
