### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by fgimenez** [RichardKnop/machinery#361]
Hi, I get this on any command that involves building:
```
$ go run example/machinery.go -c example/config.yml worker
go: finding github.com/garyburd/redigo v2.0.0+incompatible
go: github.com/garyburd/redigo@v2.0.0+incompatible: unknown revision v2.0.0
go: error loading module requirements
```
According to https://github.com/gomodule/redigo/issues/366, `github.com/garyburd/redigo@v1.6.0` should be used, I'll propose a PR.

Thx!

**Comment by RichardKnop** [comment]
@fgimenez I have merged your PR but I couldn't reproduce the issue on my development machine.

```sh
go run example/machinery.go -c example/config.yml worker
```

Works for me also on version before the PR was merged. I don't have time to investigate further though.

**Comment by fgimenez** [comment]
Thanks @RichardKnop! You would probably have garyburd/redigo v2.0.0 already in the cached modules from a build when it was available, try again after deleting (or renaming) `${GOPATH}/pkg/mod` and you should get the error.

Cheers!
