### ISSUE TITLE
Custom task types?

### ISSUE THREAD

**Issue by knrt10** [RichardKnop/machinery#379]
Is there any way to create a custom task type while defining `[]tasks.Args`. Example given below

```
&tasks.Signature{
		Name: "test",
		Args: []tasks.Arg{
			{
				Type:  "context.Context",
				Value: ctx,
			},
```

I want `Type` to be my own predefined type `context.Context` or anything I want other than the list of types. Is there any way to do that? cc @RichardKnop

**Comment by seonixx** [comment]
There seems to be quite a long discussion about this - short story is you can do something opentrace, but context type support that was added some time ago appears to just add an empty context to the job when received.

**Comment by seonixx** [comment]
https://github.com/RichardKnop/machinery/issues/175

**Comment by knrt10** [comment]
Thanks @seonixx I solved it using [#293](https://github.com/RichardKnop/machinery/issues/293)

**Comment by seonixx** [comment]
@knrt10 are you using an opentrace span within the context or just a normal context type?

**Comment by knrt10** [comment]
Actually, I did not want to pass a context. I had a model for a struct, I needed to pass that. Context was just an example of what I wanted.

**Comment by kaelwzm** [comment]
@knrt10 consider json.encode(obj)? Using string type, and decode it when consuming.
