### ISSUE TITLE
Redis result backend starts hanging when creating new jobs after using version later then 1.5.5

### ISSUE THREAD

**Issue by barthr** [RichardKnop/machinery#396]
*Setup:*

We setup machinery using version 1.5.6 with result backend redis and broker AMQP. We run 1 worker with concurrency set to 10. We have 1 publisher (our web process).

*Actual:*
When enqueing a job, the job should be created in redis (redis was available from both the command line and the container), however the process started hanging. The job wasn't created in redis and also not enqeueued as a result.

*Expected:*

Job should be added to redis and worker should be able to pick up the enqueued job on rabbitmq. Redis should have the job state stored.

**NOTE this actually works with version 1.5.5**

When going through the commits I didn't find any code related to redis or result backend changes in 1.5.6, however there were a lot of dependencies changed in the go.mod, this makes it very tedious to find the actual issue, since it could be any of the dependencies.

**Comment by RichardKnop** [comment]
@barthr Can you try updating to 1.6.0?

Integration tests with redis backend seem to pass so not sure what could be problem. I pruned and tidied up dependencies in go.mod and go.sum files. Maybe it will help.

Also, are you using Go modules?

**Comment by barthr** [comment]
We are using go modules, also 1.6.0 doesn't seem to work. I think it's a indirect dependency causing the issues.
