### ISSUE TITLE
Publisher doesn't reconnect to broker (rabbit mq)

### ISSUE THREAD

**Issue by ilyamochalov** [RichardKnop/machinery#411]
Setup:
We setup machinery using version 1.6.2 with result backend redis and broker RabbitMQ. We run 5 worker with concurrency set to 10. We have 1 publisher (our web process which is embedded in iris framework). We test if publisher reconnects to RabbitMQ in case of dropping connection (we turn down MQ process for some time and turn it back on after some time) 

Actual:
Worker processes are able to reconnect to RabbitMQ. Publisher process is not able to reconnect (even after long time), reusing previously created publisher server process results into error `Could not send task: %sSet state pending error: Dial error: Exception (501) Reason: "EOF"`

Expected:
Worker and publisher should reconnect to RabbitMQ, in case connection was propped for some time.

**Comment by piotrkochan** [comment]
Answer for this question is very important for me
