### ISSUE TITLE
redis key may never expire

### ISSUE THREAD

**Issue by yuzhiyuxia** [RichardKnop/machinery#413]
In redis backend, The commands **SET**and **EXPIREAT** in different operations may cause the key never expires. Why do not use this command:
**SET key value [expiration EX seconds|PX milliseconds] [NX|XX]**

Another question:
For Chords, ChordCallback is **executed at most once** ?
In taskSucceeded function, it firstly set ChordTriggered true, then send  ChordCallback task! 
There may be set successfuly, but send fail. so ChordCallback is not executed.

**Comment by yuzhiyuxia** [comment]
In taskSucceeded  function, we don't care OnSuccess task?
What is the precondition for using machinery?

**Comment by charleswhchan** [comment]
@yuzhiyuxia : would you be willing to create a PR to address these issues? 😃
