### ISSUE TITLE
Use signature's routing key as binding key for AMQP broker with direct exchange type

### ISSUE THREAD

**Issue by Martin91** [RichardKnop/machinery#419]
### Background
In our project, we are using RabbitMQ as the broker, and we need to group tasks into different queues.

I am newbie in both Golang and Machinery, and I am not so sure if it is a problem actually.

### Environment
1. A clean RabbitMQ vhost, no queue, no exchange before, and we are using direct exchange
2. Golang v1.12
3. Machinery v1.6.2

### Steps To Reproduce
1. Specify individual routing keys in the signatures of different types of tasks, meanwhile, some tasks kept implicit routing key;
2. Run some tests to push tasks;
3. Visited the RabbitMQ Management console http://localhost:15672/#/queues, I found there were some new queues, it was expected;
4. Then I navigated the exchange page http://localhost:15672/#/exchanges/%2F/machinery_exchange,  I found that all queues were binded to the exchange with the same binding key `machinery_task`, which is exactly configured as a binding key to initialize the Machinery server;
5. Fetch messages from the queues, only messages with implicit routing key (default routing key) were there, it means that I missed messages which sent with a custom routing key

### What To Expect
For direct AMQP exchange:

1. It can declare new queues and bind them to the exchange use dynamically specified routing key.

### My Idea
I have explored the source code and I think it might be possible to do this:

1. Pass routing key as both queue name and binding key to method `GetOrOpenConnection`, instead of configured `DefaultQueue` and `bindingKey`;

  the original code(note: the referenced code is based on v1.6.4) is:
 
 https://github.com/RichardKnop/machinery/blob/3a69c03c4fa63b8a60157979773b2afed80549a9/v1/brokers/amqp/amqp.go#L202-L208

  and can be changed to:
```go
// isDirectChange extracted function to be reusable
func (b *Broker) isDirectExchange() bool {
	return b.GetConfig().AMQP != nil && b.GetConfig().AMQP.ExchangeType == "direct"
}

func (b *Broker) Publish(ctx context.Context, signature *tasks.Signature) error {
	// ... something else
	var queue string
	var bindingKey string
	if b.isDirectExchange() {
		queue = signature.RoutingKey
		bindingKey = signature.RoutingKey
	} else {
		queue = b.GetConfig().DefaultQueue,
		bindingKey = b.GetConfig().AMQP.BindingKey, // queue binding key
	}

	connection, err := b.GetOrOpenConnection(
		queue,
		bindingKey,
		nil,                           // exchange declare args
		nil,                           // queue declare args
		amqp.Table(b.GetConfig().AMQP.QueueBindingArgs), // queue binding args
	)
	// something else
}
```

**Comment by Martin91** [comment]
After thinking other solutions, I find another solution to solve my problem, that is, I can create multiple servers and each of them use exactly only one routing key and queue name, besides, multiple workers are also necessary to handle tasks registered by different servers and enqueued in different queues. However, I think it's too coupled.

**Comment by julianwachholz** [comment]
Hi @Martin91!
I was facing the same issue but found a _clean-ish_ solution without having to change anything in machinery.

My code has a dispatcher and worker part. I pull the default configuration from a file that looks identical to [the example](https://github.com/RichardKnop/machinery/blob/9a3ed8e8a371639524ec8c7f9354404e63d22240/example/config.yml).

Registering the tasks works as usual, the important part happens when starting a worker. Each worker gets an optional bindingKey argument (e.g. `workerBindingKey`).
After loading the config from the Yaml file, I overwrite the binding key and create a separate queue for the worker so I start it like this:
```
cnf.AMQP.BindingKey = "image_resize"
worker := server.NewCustomQueueWorker("image_resizer", 0, "tasks_image_resize")
```
In this case I just use the same name for the queue and binding key. Now when sending a task, I overwrite the RoutingKey:
```
server.SendTask(&tasks.Signature{
  Name: "ResizeImage",
  RoutingKey: "image_resize",
})
```

I'm quite new to Go but so far this seems to be working as intended, most importantly with multiple workers on a queue and routing key.

**Comment by Martin91** [comment]
@julianwachholz yes, it works, but with some side effect.

According to the source code at the revision when I reported this issue, once you sending a task, it will automatically try to create a new binding between the exchange and the queue, the binding key and the queue's are exactly same.

However, your task server also create the binding between the exchange and your expected queue `"tasks_image_resize"`.

That is, once you sending a task, a message is sent to both `image_resize` queue and `tasks_image_resize` queue. But messages in `image_resize` are never consumed. You can log in your RabbitMQ web console http://localhost:15672/#/queues to check.

However, @RichardKnop has merged my PR https://github.com/RichardKnop/machinery/pull/420 , it resolved the problem and also implemented the feature I needed.
