### ISSUE TITLE
AMQP delayed queues take too long to be deleted

### ISSUE THREAD

**Issue by NicolasWalter** [RichardKnop/machinery#425]
### Summary

We are using AMQP as broker, and delaying the execution of tasks setting ETAs days after they are created.
 For example, we set a task's ETA in 5 days, and that queue is going to expire in 10 days, because the eta value is multiplied by 2 here: https://github.com/RichardKnop/machinery/blob/master/v1/brokers/amqp/amqp.go#L354 .

We need to be able to change that value to avoid having thousands of empty queues for days.

### Ideas

- add an extra value to `AMQPConfig` struct.
- add an extra value to `Signature` struct.
- add a new public function that works as `SendTask` but taking this value as a parameter and passing it to `delay` function. 

Thanks!

**Comment by NicolasWalter** [comment]
Hi again, I also found that would be useful to be able to change the autodelete value: https://github.com/RichardKnop/machinery/blob/master/v1/brokers/amqp/amqp.go#L370

If you agree, the previous solutions can be extended with this value as well.

**Comment by RichardKnop** [comment]
@NicolasWalter This seems like a good idea. If you need this feature quickly it's best to submit PR :)

**Comment by humjosh** [comment]
@NicolasWalter I'm curious if this change worked as intended? My understanding is that the AMQP auto-delete setting deletes the queue when it has no consumers, not when the queue has no messages? If the queue never had any consumers (which is the case for the delay function in machinery), this setting will have no effect.
