### ISSUE TITLE
Secret Information is logged when new worker is launched.

### ISSUE THREAD

**Issue by yolossn** [RichardKnop/machinery#438]
**Problem:**
When a new worker is launched the `LaunchAsync` function is called internally and it logs the configuration of the worker which exposes my AMQP URL and ResultBackend URL which is not ideal in any production environment. [Code](https://github.com/RichardKnop/machinery/blob/92b1e367570d5cae7e4adc086af84381fa09c01b/v1/worker.go#L55)

**Example log:**

> INFO: 2019/07/10 10:27:00 worker.go:46 Launching a worker with the following settings:
> INFO: 2019/07/10 10:27:00 worker.go:47 - Broker: amqp://guest:guest@rabbitmq:5672
> INFO: 2019/07/10 10:27:00 worker.go:49 - DefaultQueue: test
> INFO: 2019/07/10 10:27:00 worker.go:53 - ResultBackend: mongodb://mongodb:27017/test
> INFO: 2019/07/10 10:27:00 worker.go:55 - AMQP: broker
> INFO: 2019/07/10 10:27:00 worker.go:56   - Exchange: broker
> INFO: 2019/07/10 10:27:00 worker.go:57   - ExchangeType: direct
> INFO: 2019/07/10 10:27:00 worker.go:58   - BindingKey: test
> INFO: 2019/07/10 10:27:00 worker.go:59   - PrefetchCount: 1

**Possible Solutions:**
1. Redact and log secret values like `amqp://gu***:gu***@rabbi***:5672`.
2. Set a log level in the machinery server configuration so that the developer can opt to not Print INFO level logs in Production environments.

@RichardKnop  What is your take on this ? We are planning to use machinery extensively in our organization and are ready to contribute.

**Comment by RichardKnop** [comment]
@yolossn I think the values should be redacted, this is an oversight. If you want to submit PR, it would be a good addition.

Alternatively, you can modify logging behaviour by setting your own logger before calling `LaunchAsync`: https://github.com/RichardKnop/machinery#custom-logger

**Comment by yolossn** [comment]
@RichardKnop Hey thanks for taking your time out to reply. I will make a PR for redacted logging of values. I did come across the custom-logger but didn't find anything related to setting log level for the machinery server itself, Am I missing anything here ?

**Comment by RichardKnop** [comment]
You could create a no operation (NOP) logger and do `log.SetInfo(nopLogger)`, then all `INFO` logs would be ignored.

**Comment by yolossn** [comment]
Yes that will work,my bad didn't think of that.

**Comment by yolossn** [comment]
@RichardKnop I submitted the PR https://github.com/RichardKnop/machinery/pull/441, but the ci build is failing due to timeout.

**Comment by charleswhchan** [comment]
As the PR had been merged. Perhaps this ticket can be closed?

**Comment by yolossn** [comment]
Yes! closing this.
