### ISSUE TITLE
Worker of redis broker quit very slow

### ISSUE THREAD

**Issue by Liv1020** [RichardKnop/machinery#439]

**Comment by charleswhchan** [comment]
I am also seeing the same issue.

**Comment by Liv1020** [comment]
@charleswhchan I loook for code of redis, found use `conn.Do("BLPOP", queue, 1000)`, this will block goroutine.
https://github.com/RichardKnop/machinery/blob/master/v1/brokers/redis/redis.go#L294

**Comment by RichardKnop** [comment]
@Liv1020 Can you submit fix as PR? Would be appreciated.

**Comment by charleswhchan** [comment]
Yes, please submit a PR if possible.  😀

(Also, please do not close the issue yet because the bug has not yet been fixed. Thanks)

**Comment by RichardKnop** [comment]
There were some changes to Redis broker here: https://github.com/RichardKnop/machinery/pull/406

The changes apparently decreased CPU consumption 15 times so it would be good to keep this in mind, some of these changes had a good reason.

This should be fixed without affecting performance / CPU usage.

**Comment by charleswhchan** [comment]
@RichardKnop : do you have permission to re-open this issue so that it will show up in the list of open tickets?

**Comment by RichardKnop** [comment]
Reopened.

**Comment by Liv1020** [comment]
I will fix it, [#406 ](https://github.com/RichardKnop/machinery/pull/406) have reference value

**Comment by Liv1020** [comment]
@RichardKnop  you can merge it for a new version? we use this library

**Comment by Liv1020** [comment]
@RichardKnop have any response?

**Comment by charleswhchan** [comment]
I would also like a Machinery release with this fix.

**Comment by tcnleung** [comment]
This fix would be very nice to to have. Thank you @RichardKnop!

**Comment by charleswhchan** [comment]
@Liv1020, @RichardKnop : I tested the fix and it is working for me.
