### ISSUE TITLE
Builds are failing due to outdated dependencies.

### ISSUE THREAD

**Issue by yolossn** [RichardKnop/machinery#460]
My builds were failing and after some debugging found out that `git.apache.org/thrift.git` has been moved to `github.com/apache/thrift/` as mentioned in https://thrift.apache.org/lib/go. Thrift is an indirect dependency which was used in older version(v.0.36.0) of `cloud.google.com/go`. This version is used by machinery which is causing the builds to fail.

![Screenshot](https://user-images.githubusercontent.com/22731013/64153044-8e7df800-ce4b-11e9-953e-ce4f1650a06b.png)

**Comment by RichardKnop** [comment]
Should be fixed by recently merged PR https://github.com/RichardKnop/machinery/pull/462
