### ISSUE TITLE
Mismatch default DelayedTasksPollPeriod 

### ISSUE THREAD

**Issue by charleswhchan** [RichardKnop/machinery#465]
In https://github.com/RichardKnop/machinery/blob/master/v1/config/config.go#L44
```
			DelayedTasksPollPeriod: 20,
```

In https://github.com/RichardKnop/machinery/blob/6f7b63c9a5dbb8c18444aff89d22578efe4c39b0/v1/brokers/redis/redis.go#L331
```
	pollPeriod := 500 // default poll period for delayed tasks
```

Given `NormalTasksPollPeriod:  1000`, I suspect the default for `DelayedTasksPollPeriod` is incorrect and should be 500 as specified in redis.go?

**Comment by charleswhchan** [comment]
Also 20 seems too short given this comment in the [code](https://github.com/RichardKnop/machinery/blob/6f7b63c9a5dbb8c18444aff89d22578efe4c39b0/v1/brokers/redis/redis.go#L359):
```
		// Space out queries to ZSET so we don't bombard redis
		// server with relentless ZRANGEBYSCOREs
		time.Sleep(time.Duration(pollPeriod) * time.Millisecond)
```

**Comment by RichardKnop** [comment]
I think you are correct. This seems like a mistake, it should be 500.
