### ISSUE TITLE
Default settings in RedisConfig not optimal for connection pooling

### ISSUE THREAD

**Issue by charleswhchan** [RichardKnop/machinery#469]
From: https://godoc.org/github.com/RichardKnop/machinery/v1/config#RedisConfig
```
type RedisConfig struct {
    // Maximum number of idle connections in the pool.
    MaxIdle int `yaml:"max_idle" envconfig:"REDIS_MAX_IDLE"`

    // Maximum number of connections allocated by the pool at a given time.
    // When zero, there is no limit on the number of connections in the pool.
    MaxActive int `yaml:"max_active" envconfig:"REDIS_MAX_ACTIVE"`

    // Close connections after remaining idle for this duration in seconds. If the value
    // is zero, then idle connections are not closed. Applications should set
    // the timeout to a value less than the server's timeout.
    IdleTimeout int `yaml:"max_idle_timeout" envconfig:"REDIS_IDLE_TIMEOUT"`

    // If Wait is true and the pool is at the MaxActive limit, then Get() waits
    // for a connection to be returned to the pool before returning.
    Wait bool `yaml:"wait" envconfig:"REDIS_WAIT"`
```

During load testing, we found that Machinery was opening/closing lots of new Redis connections every time `SendTask()` is called. This lead to major CPU load for Redis and eventually exhaust the max number of client connections as the Redis process has trouble keeping up with all the open/close connections.

Looking the [documentation](https://godoc.org/github.com/RichardKnop/machinery/v1/config#RedisConfig) and [code](https://github.com/RichardKnop/machinery/blob/a9db7ae5adee6615431cd96b5ddae218951848c3/v1/common/redis.go#L11), the result makes sense because MaxActive is 0 (unlimited), and MaxIdle is 0 (close immediately). 

Perhaps a better setting out of the box is to setup a small pool of connections? Especially MaxActive

Suggestion:
```
MaxActive = 100
Wait = true
MaxIdle = 10
IdleTimeout = 10
```

Thoughts?

**Comment by RichardKnop** [comment]
@charleswhchan This seems sensible, probably a good idea 👍

**Comment by charleswhchan** [comment]
Thanks @RichardKnop. I will put up a PR for it in a bit.

**Comment by theholy7** [comment]
What is the status of this ticket?

**Comment by charleswhchan** [comment]
Merged to master. 

See commit https://github.com/RichardKnop/machinery/commit/ec54a187c6b2bf3f5951f992f08c193446d5b12c
