### ISSUE TITLE
Option to not delete task on task failure (Useful for SQS DLQ)

### ISSUE THREAD

**Issue by Uzair614** [RichardKnop/machinery#471]
Currently, if a task fails during processing, then machinery either

1. Resends the tasks, and if successful, deletes from the source queue (if retries are enabled)
2. Just deletes the tasks (if retries are disabled or exhausted)

I propose to add another option to not delete tasks if tasks have failed. This is useful for if you are using SQS and have DLQ enabled on your queues. With machinery's internal retry mechanism of deleting the old task and resending a new task, DLQ in SQS is not triggered. With this new option in the task signature, you'd have the option to disable task deletion and the message would automatically move to DLQ (if you've configured it) after the AWS specified retries.

**Comment by Uzair614** [comment]
@RichardKnop can you also please tag a new version for use in go.mod? Thank you

**Comment by RichardKnop** [comment]
Will do.

**Comment by mostafazh** [comment]
I think this can be closed
