### ISSUE TITLE
Insanely high CPU usage on the Redis adapter.

### ISSUE THREAD

**Issue by rvera** [RichardKnop/machinery#49]
Seems like the Redis adaptor is using `LPOP` instead of `BLPOP` which leads to super busy polling.

**Comment by RichardKnop** [comment]
@rvera Hi. I'm quite busy with another project at the moment so might not have time to look at this in near future. If you want to refactor the Redis adaptor, feel free to issue a PR :)

**Comment by RichardKnop** [comment]
@rvera Although there is a reason why BLPOP is used. Using LPOP means multiple workers can process a task at the same time which would require tasks to be idempotent. I didn't want to force people to define idempotent tasks and instead make sure in the library each task is processed just once, hence BLPOP. If you have a different solution which works, feel free to submit a PR.

**Comment by waterlink** [comment]
@RichardKnop I can't 100% understand what are you saying in your last comment. It seems like, you are advocating the use of `BLPOP` since it allows users of the library to not care about idempotency in their tasks.

What puzzles me is that the code in question actually using `LPOP`, not `BLPOP`. Can you clarify a bit, I am, most probably, misunderstand something.

**Comment by roee-indegy** [comment]
I have encountered this issue as well. BLPOP has a timeout parameter which makes it behave similarly to LPOP. So I just changed the call to BLPOP with a timeout. The response you get is a little different but it's documented quite well here: http://redis.io/commands/BLPOP

**Comment by RichardKnop** [comment]
@roee-indegy Do you want to create a PR? :)

**Comment by parhamdoustdar** [comment]
Why would `LPOP` increase CPU usage while `BLPOP` wouldn't?

**Comment by roee-indegy** [comment]
@parhamdoustdar Using LPOP causes the goroutine to busy wait (constantly sampling the socket to see if there's a change) whereas using the blocking call causes the goroutine to enter a waiting state thus relinquishing its resources till the socket gets a reply from redis. It's similar to the difference between a spin lock and a regular mutex.

**Comment by parhamdoustdar** [comment]
@roee-indegy Thanks a lot for the explanation!

**Comment by RichardKnop** [comment]
This should be solved by this PR: https://github.com/RichardKnop/machinery/pull/61

If it is indeed solved, I will close this issue. Let me know if it works for everybody.

**Comment by parhamdoustdar** [comment]
This works perfectly fine for me.
