### ISSUE TITLE
A kafka broker

### ISSUE THREAD

**Issue by F21** [RichardKnop/machinery#50]
I think it would be really awesome if Kafka can be added as a broker. I am currently investigating using kafka to send messages as part of an event-sourced system on mesos. Being able to use kafka would mean that existing kafka infrastructure can be used, rather than having to build a AMQP cluster on mesos.

**Comment by RichardKnop** [comment]
@F21 Feel free to submit a PR that adds a Kafka broker. At the moment I am busy with another project so it is not likely I will have time to do this myself.

**Comment by RichardKnop** [comment]
@F21 I am closing this for now but am open to a PR adding new broker.

**Comment by FelixSeptem** [comment]
any progress or plan about use kafka as a broker？for kafka has been a popular stream system

**Comment by pfortin-urbn** [comment]
I think this should be opened and put on the roadmap.
