### ISSUE TITLE
Increased cpu usage over time

### ISSUE THREAD

**Issue by makkalot** [RichardKnop/machinery#505]
Hi,

I've been using machinery in one my client's projects and seen this weird behaviour where if have consumer which processes lots of tasks, over time it's cpu consumption increases and the processing of the tasks slows down dramatically. I'm attaching a screen of the behaviour. We're using 1.6.9 version with redis as broker and backend. Any ideas ?
<img width="538" alt="Screenshot 2019-12-20 at 08 29 08" src="https://user-images.githubusercontent.com/8519/71234963-579cf680-2303-11ea-8d83-c4a2079731fc.png">

**Comment by RichardKnop** [comment]
Can you do some profiling to see what's consuming the CPU?

**Comment by makkalot** [comment]
Thanks for the response, did some profiling, turned out it was something from our handlers a memory leak causing a data structure to grow and eventually putting load on cpu when working. Can safely close the issue, sorry for the noise :)
