### ISSUE TITLE
Chords are not triggered sometimes when using DynamoDB backend

### ISSUE THREAD

**Issue by gow** [RichardKnop/machinery#525]
I have noticed that sometimes, the chord callbacks are not executed when using DynamoDB as the backend. Upon further inspection with some debug logging, I noticed that in some instances `GroupCompleted()` returns false even when there was only one task in the group.  `GroupCompleted()`  is called in response to a task being completed. So this should never return false in such instances.
Along with this, I also noticed that sometimes `GroupCompleted()` returns false when all the tasks in the group have been completed.
This is happening mainly due to inconsistent reads. AWS dynamoDB supports 2 types of reads - https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadConsistency.html
  - Eventually Consistent Reads
  - Strongly Consistent Reads

To check if a group is complete, we must use strongly consistent reads. Otherwise we may read the stale state and miss triggering the chord. There there is no inbuilt mechanism to retry the group completion check, we should use strongly consistent reads here. Thoughts?

I suspect this is happening in other storages as well where the default reads are eventually consistent.

**Comment by gow** [comment]
I'm thinking of making all DynamoDB reads strongly consistent here. Mainly because it implements locking of groups using eventually consistent reads and this will lead to incorrect locking.

I'll send a PR making all reads use strong consistency unless others have a different opinion.

**Comment by RichardKnop** [comment]
Hopefully this will be fixed by https://github.com/RichardKnop/machinery/pull/527

**Comment by gow** [comment]
This is fixed.
