### ISSUE TITLE
If redis crashes a worker won't quit

### ISSUE THREAD

**Issue by ghost** [RichardKnop/machinery#53]
```go
	redisBroker.pool = redisBroker.newPool()
	defer redisBroker.pool.Close()

	_, err := redisBroker.pool.Get().Do("PING")
	if err != nil {
		redisBroker.retryFunc()
		return true, err // retry true
	}
```

I have a test case where i see how my program handles redis crashes. Once i identify the crash, i want to close the worker and create a new one since redis's ip might've changed.
So when redis crashes, i try to call Quit() in the hope of stopping the previous worker goroutine. The stopping channel isn't sampled, so the worker won't quit since it'll keep on retrying.

**Comment by roee-indegy** [comment]
Also since the stopRecv channel is overwritten every iteration of StartConsume, if i sent a quit request during that time it won't ever happen even when a reconnecting attempt succeeds

**Comment by RichardKnop** [comment]
@roee-indegy Hi. Yes Redis has been the second broker after RabbitMQ and the implementation is a bit quick and dirty (leaving a lot to be desired). If you think this is relatively simple to fix, you can submit a PR. I'd be happy to merge it!

**Comment by RichardKnop** [comment]
@roee-indegy Does this fix the issue?

**Comment by roee-indegy** [comment]
Not really, the channels are blocked till the consuming goroutine reads from the channels. So the consuming goroutine will exit, but the caller to Quit will be blocked by writing to the channel.

**Comment by RichardKnop** [comment]
@roee-indegy Alright, sorry. I will look into this more closely if I get more free time but I will be quite busy next few weeks so I can't guarantee it will be fixed soon. If you have a fix for it already, submit a PR :)

**Comment by roee-indegy** [comment]
I bypassed the problem by publishing the redis server's port, that way i refer to the same ip and i don't have to use quit. I played around with some patches, none of them worked so well. I'll see what i can do about it :)

**Comment by RichardKnop** [comment]
@ghost I am closing this for now. If you have managed to find a way to fix this please open a PR. I will reopen this if other people encounter the same issue.
