### ISSUE TITLE
release v1.7.5 with better dynamodb support

### ISSUE THREAD

**Issue by roopakv** [RichardKnop/machinery#530]
Could you please release a new version with this commit:

https://github.com/RichardKnop/machinery/commit/107e5de255d42fbeafc2494866f1b419bae9e3b5

**Comment by charleswhchan** [comment]
Hi @roopakv, I see v1.7.5 had been released on Apr 20: 
https://github.com/RichardKnop/machinery/releases/tag/v1.7.5

Could you close this issue? :smiley:
