### ISSUE TITLE
Is there some way to interrupt a running task(long enough) ?

### ISSUE THREAD

**Issue by jetora** [RichardKnop/machinery#531]
Is there some way to interrupt a running task(long enough) ?

like：

celery：
from celery.task.control import revoke
revoke(id, terminate=True)

**Comment by gow** [comment]
In Go, you should use contexts with deadline to achieve this. And your task must be cooperiating (i.e listen on ctx.Done() and take action)

See below links for further information:

- https://golang.org/pkg/context/#WithDeadline
- https://blog.golang.org/context

**Comment by Mrliu8023** [comment]
Hello, has machinery implemented passing context yet?
