### ISSUE TITLE
Is there a way to control the rate of processing of jobs

### ISSUE THREAD

**Issue by shivanshgaur** [RichardKnop/machinery#532]
We want to control the rate of consumption of messages from the queue.  We are using Redis as a broker. I know I can check the rate of message consumption after it gets popped from the queue. But I explicitly want to pop only when the rate limiter allows me to do it.

**Comment by gow** [comment]
This is an interesting problem. I'm dealing with it too. But I wonder if machinery is the right place for this. There are a lot of open questions.
  - What about required infrastructure? Distributed coordination needs specialized tools to implement correctly (Ex: etcd, consul, zookeeper etc). I don't think Machinery can reliably implement a rate limiter across all the supported broker/backend configurations.
  - Should the task be retried immediately? If not what is the backoff policy?
  - What about thundering herd effect? i.e if there are N tasks and only one can be run currently, how does the framework make sure that the rest N-1 tasks are not retried approximately the same time? Maybe add a jitter to whatever backoff time is chosen to spread them out?


I propose the following,
1) Machinery to provide a way for us to register a rate limiter. The rate limiter would be an interface that takes the task-state as a parameter and returns a bool return value (no errors - they are handled internally).
2) Machinery then checks the rate limiter (if one is configured) with the currently popped task state. If the rate limiter returns negative, it puts the task back into the queue with an exponential backoff + some jitter.

This way we can manage our own infrastructure how ever we see fit. For example, if you are running machinery on a single instance, the rate limiter could be a simple semaphore within Go runtime. If you run on multiple nodes, you can use one of etcd, consul etc to manage a more sophisticated rate limiter.
