### ISSUE TITLE
Possible deadlock when getting connection from redigo pool

### ISSUE THREAD

**Issue by flf2ko** [RichardKnop/machinery#546]
When I tried to do load test to create massive amount of group of tasks, I found it could block at `SendGroupWithContext()` . I found the root cause may comes from get connection from pool twice or more in a function.

for example:
https://github.com/RichardKnop/machinery/blob/master/v1/backends/redis/redis.go#L57-L65

```
func (b *Backend) InitGroup(groupUUID string, taskUUIDs []string) error {
	groupMeta := &tasks.GroupMeta{
		GroupUUID: groupUUID,
		TaskUUIDs: taskUUIDs,
		CreatedAt: time.Now().UTC(),
	}

	encoded, err := json.Marshal(groupMeta)
	if err != nil {
		return err
	}

	conn := b.open()    <----- get connection
	defer conn.Close()

	_, err = conn.Do("SET", groupUUID, encoded)
	if err != nil {
		return err
	}

	return b.setExpirationTime(groupUUID)   <----- get connection again in this function
}
```

This function call actually try to get connection twice. 
So in some cases (e.g. massive InitGroup were called), all connection could be given to first step and the second step could block forever.

I proposed a possible solution in my fork repository. All exported function will get connection once and pass it to all unexported function in argument.

https://github.com/flf2ko/machinery/commit/29bf65e0cdd82e981f2f7ed54319cfa837f25518

If you have any suggestion or need a pull request, that will be great. Thanks!
(btw I love this project a lot : ) )

**Comment by RichardKnop** [comment]
@flf2ko Hi. The solution in your fork looks good. Can you create a PR? :)
