### ISSUE TITLE
 Redis SSL

### ISSUE THREAD

**Issue by yap-studios** [RichardKnop/machinery#570]
Good day,

Is there a reason why redis connection strings that starts with **rediss**:// instead of redis:// are not supported for the factories?

**Comment by charleswhchan** [comment]
The factory currently looks for the prefix "redis://": https://github.com/RichardKnop/machinery/blob/master/v1/factories.go#L41

Looking at the underlying Redis libraries, both of them supports `rediss://`:
- redigo https://github.com/gomodule/redigo/pull/208
- go-redis https://github.com/go-redis/redis/pull/420

It should be pretty easy to modify the factory to support this. Want to give this a try and create a PR for it?

**Comment by yap-studios** [comment]
Okay. Yeah I'll give it a try today.

**Comment by yap-studios** [comment]
@charleswhchan, I've submitted a PR. Could you please review it? Thanks.

**Comment by charleswhchan** [comment]
Yeah. PR looks reasonable to me.

**Comment by yap-studios** [comment]
Great, thanks. Do you have a timeline of when you'll be able to merge it? We are preparing to go into production.

**Comment by charleswhchan** [comment]
@yap-studios : sorry but I don't have permission. Please check with @RichardKnop. 😃

**Comment by yap-studios** [comment]
@RichardKnop, Do you have any plans to merge the PR?
