### ISSUE TITLE
Converting `error` to type `string` has weird consequences

### ISSUE THREAD

**Issue by parhamdoustdar** [RichardKnop/machinery#59]
When my function is called and it returns an error, it is converted to string, rather than an error. This causes `error` to be a string containing `<error Value>`. Here is an example:

```
result, err := asyncResult.Get()
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		log.Println(err)
		return
	}
```

When I run this, I see `<error Value>` in the log where I print `err`. It is because in `worker.go`, on line 92, the second returned argument is converted to `string`, and the string representation of an `error` type is `<error Value>`.

**Comment by parhamdoustdar** [comment]
Here are the changes I've made to make this work for me. I'm not sure if they are acceptable though, so I'm pasting the diff here:

```
diff --git a/v1/worker.go b/v1/worker.go
index 41d4d42..db6dbf3 100644
--- a/v1/worker.go
+++ b/v1/worker.go
@@ -1,7 +1,6 @@
 package machinery
 
 import (
-	"errors"
 	"fmt"
 	"log"
 	"reflect"
@@ -89,7 +88,7 @@ func (worker *Worker) Process(signature *signatures.TaskSignature) error {
 	// Call the task passing in the correct arguments
 	results := reflectedTask.Call(relfectedArgs)
 	if !results[1].IsNil() {
-		return worker.finalizeError(signature, errors.New(results[1].String()))
+		return worker.finalizeError(signature, results[1].Interface().(error))
 	}
 
 	return worker.finalizeSuccess(signature, results[0])

```

**Comment by RichardKnop** [comment]
@parhamdoustdar Can you open a PR and see if tests pass? It seems good on first glance.

**Comment by parhamdoustdar** [comment]
Pull request done. All tests pass:

https://github.com/RichardKnop/machinery/pull/60
