### ISSUE TITLE
Cannot create server with redis broker and backend due to "Factory failed with lock:"

### ISSUE THREAD

**Issue by Kamforka** [RichardKnop/machinery#610]
For some reason I cannot create a `machinery` server with Redis backend and broker.
This is the snippet I'm using:

```go
package main

import (
	"fmt"

	"github.com/RichardKnop/machinery/v1"
	"github.com/RichardKnop/machinery/v1/config"
)

func main() {

	server, err := machinery.NewServer(&config.Config{
		Broker:        "redis://localhost:6379",
		ResultBackend: "redis://localhost:6379",
	})
	if err != nil {
		fmt.Println(err.Error())
		panic(err)

	}
}
```

When I run it I get the following error:
```bash
panic: Factory failed with lock: 

goroutine 1 [running]:
main.main()
        /home/<...>/server.go:18 +0x416
```

The redis instance is running in on my host inside a docker container, and I verified that it is functional as I can retrieve keys, set and get values etc.

Any clues what can cause the issue?

---
*System Info:*

- Ubuntu 20.04.1 LTS
- go version go1.13.4 linux/amd64
- github.com/RichardKnop/machinery v1.9.4

**Comment by RichardKnop** [comment]
Will fix, thanks for spotting.
