### ISSUE TITLE
go get github.com/RichardKnop/machinery/v1: module github.com/RichardKnop/machinery@upgrade found (v2.0.4+incompatible), but does not contain package github.com/RichardKnop/machinery/v1

### ISSUE THREAD

**Issue by iiiusky** [RichardKnop/machinery#649]
go get github.com/RichardKnop/machinery/v1: module github.com/RichardKnop/machinery@upgrade found (v2.0.4+incompatible), but does not contain package github.com/RichardKnop/machinery/v1

**Comment by iiiusky** [comment]
`➜ go get github.com/RichardKnop/machinery/v2
go: downloading github.com/RichardKnop/machinery/v2 v2.0.4
go: github.com/RichardKnop/machinery/v2 upgrade => v2.0.4
go: finding module for package github.com/RichardKnop/machinery/v1/locks/iface
go: finding module for package github.com/RichardKnop/machinery/v1/log
go: finding module for package github.com/RichardKnop/machinery/v1/tracing
go: finding module for package github.com/RichardKnop/machinery/v1/utils
go: finding module for package github.com/RichardKnop/machinery/v1/backends/amqp
go: finding module for package github.com/RichardKnop/machinery/v1/retry
go: finding module for package github.com/RichardKnop/machinery/v1/tasks
go: finding module for package github.com/RichardKnop/machinery/v1/brokers/errs
go: finding module for package github.com/RichardKnop/machinery/v1/config
go: finding module for package github.com/RichardKnop/machinery/v1/brokers/iface
go: finding module for package github.com/RichardKnop/machinery/v1/backends/iface
go: finding module for package github.com/RichardKnop/machinery/v1/backends/result
go: finding module for package github.com/RichardKnop/machinery/v1/backends/result
go: finding module for package github.com/RichardKnop/machinery/v1/tracing
go: finding module for package github.com/RichardKnop/machinery/v1/backends/amqp
go: finding module for package github.com/RichardKnop/machinery/v1/retry
go: finding module for package github.com/RichardKnop/machinery/v1/brokers/errs
go: finding module for package github.com/RichardKnop/machinery/v1/tasks
go: finding module for package github.com/RichardKnop/machinery/v1/brokers/iface
go: finding module for package github.com/RichardKnop/machinery/v1/config
go: finding module for package github.com/RichardKnop/machinery/v1/log
go: finding module for package github.com/RichardKnop/machinery/v1/utils
go: finding module for package github.com/RichardKnop/machinery/v1/locks/iface
go: finding module for package github.com/RichardKnop/machinery/v1/backends/iface
../../gopath/pkg/mod/github.com/!richard!knop/machinery/v2@v2.0.4/worker.go:15:2: module github.com/RichardKnop/machinery@latest found (v2.0.4+incompatible), but does not contain package github.com/RichardKnop/machinery/v1/backends/amqp
../../gopath/pkg/mod/github.com/!richard!knop/machinery/v2@v2.0.4/server.go:20:2: module github.com/RichardKnop/machinery@latest found (v2.0.4+incompatible), but does not contain package github.com/RichardKnop/machinery/v1/backends/iface
../../gopath/pkg/mod/github.com/!richard!knop/machinery/v2@v2.0.4/server.go:13:2: module github.com/RichardKnop/machinery@latest found (v2.0.4+incompatible), but does not contain package github.com/RichardKnop/machinery/v1/backends/result
../../gopath/pkg/mod/github.com/!richard!knop/machinery/v2@v2.0.4/worker.go:16:2: module github.com/RichardKnop/machinery@latest found (v2.0.4+incompatible), but does not contain package github.com/RichardKnop/machinery/v1/brokers/errs
../../gopath/pkg/mod/github.com/!richard!knop/machinery/v2@v2.0.4/server.go:21:2: module github.com/RichardKnop/machinery@latest found (v2.0.4+incompatible), but does not contain package github.com/RichardKnop/machinery/v1/brokers/iface
../../gopath/pkg/mod/github.com/!richard!knop/machinery/v2@v2.0.4/server.go:14:2: module github.com/RichardKnop/machinery@latest found (v2.0.4+incompatible), but does not contain package github.com/RichardKnop/machinery/v1/config
../../gopath/pkg/mod/github.com/!richard!knop/machinery/v2@v2.0.4/server.go:22:2: module github.com/RichardKnop/machinery@latest found (v2.0.4+incompatible), but does not contain package github.com/RichardKnop/machinery/v1/locks/iface
../../gopath/pkg/mod/github.com/!richard!knop/machinery/v2@v2.0.4/server.go:15:2: module github.com/RichardKnop/machinery@latest found (v2.0.4+incompatible), but does not contain package github.com/RichardKnop/machinery/v1/log
../../gopath/pkg/mod/github.com/!richard!knop/machinery/v2@v2.0.4/worker.go:18:2: module github.com/RichardKnop/machinery@latest found (v2.0.4+incompatible), but does not contain package github.com/RichardKnop/machinery/v1/retry
../../gopath/pkg/mod/github.com/!richard!knop/machinery/v2@v2.0.4/server.go:16:2: module github.com/RichardKnop/machinery@latest found (v2.0.4+incompatible), but does not contain package github.com/RichardKnop/machinery/v1/tasks
../../gopath/pkg/mod/github.com/!richard!knop/machinery/v2@v2.0.4/server.go:17:2: module github.com/RichardKnop/machinery@latest found (v2.0.4+incompatible), but does not contain package github.com/RichardKnop/machinery/v1/tracing
../../gopath/pkg/mod/github.com/!richard!knop/machinery/v2@v2.0.4/server.go:18:2: module github.com/RichardKnop/machinery@latest found (v2.0.4+incompatible), but does not contain package github.com/RichardKnop/machinery/v1/utils
`


？？？？

**Comment by RichardKnop** [comment]
Can you try with the latest release? Sorry, my changes to go modules caused this issue.

**Comment by iiiusky** [comment]
> Can you try with the latest release? Sorry, my changes to go modules caused this issue.

I will try tomorrow

**Comment by cliedeman** [comment]
For me `go get github.com/RichardKnop/machinery` installs `v1.10.2`

and trying to manually change to `v2.0.5` results in the following error

```
require github.com/RichardKnop/machinery: version "v2.0.5" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```
