### ISSUE TITLE
Unable to build example

### ISSUE THREAD

**Issue by raphaelreyna** [RichardKnop/machinery#651]
> example/v1/redis/main.go:33:5: app.Author undefined (type *cli.App has no field or method Author)
> example/v1/redis/main.go:34:5: app.Email undefined (type *cli.App has no field or method Email)
> example/v1/redis/main.go:40:15: cannot use []cli.Command literal (type []cli.Command) as type []*cli.Command in assignment

**Comment by RichardKnop** [comment]
Can you try with the latest release? Sorry, my changes to go modules caused this issue.

**Comment by raphaelreyna** [comment]
> Can you try with the latest release? Sorry, my changes to go modules caused this issue.

No worries, and yeah it seems to be working now! (same goes for #650)
