### ISSUE TITLE
Multiple worker stop consuming

### ISSUE THREAD

**Issue by smeadows53** [RichardKnop/machinery#695]
I'm using Redis with multiple workers. These workers produce results from request when a single worker is running without issue. When multiple workers are running, we see inconsistency in behavior where where workers  are not receiving any request and the task state reported is pending.

It appears that machinery may not be delivering requests when multiple workers with different task names are running concurrently?

**Comment by smeadows53** [comment]
Resolved

**Comment by Blogoslov** [comment]
@smeadows53 - how did you resolve this issue? I see the same behaviour and as example from 500 workers (redis is as a broker and as result backend) I see that only aprox. 400 tasks are working and all others are in PENDING state. Another example: 500 workers - 156 are runing and 74 in pending state but there are available more that 350 workers but I see in pending state some jobs.
Any advice?
