### ISSUE TITLE
Tasks only works with string and float64

### ISSUE THREAD

**Issue by nesizer** [RichardKnop/machinery#7]
if i try the example with 

    func Add(args ...int64) (int64, error) {
	    sum := int64(0)
	    for _, arg := range args {
	        sum += arg
	    }
	    return sum, nil
    }

i get "**Failed processing** {54740152-8C08-4F6F-BA2A-579B092E0615}. **Error = 1 is not int64**", from worker.go

i think it is because the default behavior of [encoding/json](https://golang.org/pkg/encoding/json/#Unmarshal) is when it finds a number in json and a interface in go it converts the number to float64

**Comment by RichardKnop** [comment]
Hi,

Thanks for spotting that. I have pushed fix to master. It should work now for these basic types:

- int, int8, int16, int32, int64
- uint, uint8, uint16, uint32, uint64
- float32, float64
- string

This is quite early stage project so I expect there to be more bugs.

I also need to add support for slices and maps so you can use them as task arguments.

**Comment by RichardKnop** [comment]
Hi,

Thanks for spotting that. I have pushed fix to master. It should work now for these basic types:

int, int8, int16, int32, int64
uint, uint8, uint16, uint32, uint64
float32, float64
string
This is quite early stage project so I expect there to be more bugs.

I also need to add support for slices and maps so you can use them as task arguments.
