### ISSUE TITLE
Pass struct as result value?

### ISSUE THREAD

**Issue by pgruenbacher** [RichardKnop/machinery#70]
Is there an opportunity for a task to return a struct or map value in order to pass more information. For instance if I'm doing file processing tasks, I'd like to convey information like filepaths, sizes, stats, etc. Currently I'm just writing the data to a json file and sending back a string value of the config filepath as a result. Is it problematic for passing such a struct value to chained tasks?

**Comment by RichardKnop** [comment]
Structs are difficult as all return values must be JSON serializable. Maps might be easier to support but only restricted to maps that can be represented as a valid JSON object. So the implementation might be a bit trickier.

**Comment by pgruenbacher** [comment]
Actually what I can do is just serialize the structs I need into strings manually myself using the encoding/json package for the time being. It seems similar questions are asked with Redis and the response is to serialize manually. http://stackoverflow.com/questions/27468458/go-how-to-save-and-retrieve-a-struct-to-redis-using-redigo

**Comment by RichardKnop** [comment]
This sounds like a bad design. Any tasks exposed via machinery should probably quite simple and complex logic (methods that return, accept structs) should be private and called from the simple exposed public tasks.

What I would probably do is have some sort of a `Result` struct, which has a corresponding table in your database. Just return the primary ID of result object. And then whatever code where you are handling result values should just take the primary key and fetch the object from the database.

I would suggest something similar for input arguments, just passing primary keys as argument sand fetching from database / creating structs inside the function. This should keep API clean.
