### ISSUE TITLE
Forget to close  AMQP connection

### ISSUE THREAD

**Issue by ypyf** [RichardKnop/machinery#73]
You open a connection in AMQPBroker.Publish method, but you don't close it.
Why?

**Comment by pbrazdil** [comment]
I don't get it as well. I am forced to use Redis as a backend.

**Comment by RichardKnop** [comment]
Right. Sorry for that. If you want to submit a patch, feel free to do so. I'll look into fixing this myself eventually.

**Comment by RichardKnop** [comment]
@ypyf @pbrazdil Try the latest code in master. Does it fix the issue? Let me know. Also guys, feel free to submit patches. I haven't had much time to work on maintaining this library recently.

**Comment by pbrazdil** [comment]
Thank you Richard, seems like it's working. Btw, I plan to do some PRs in the future.
