### ISSUE TITLE
Update task state with metadata

### ISSUE THREAD

**Issue by scotwells** [RichardKnop/machinery#77]
Awesome work on this project! 

Did you have any plans to add the ability for a task to update its state with metadata? I'm currently using this project to import data and it would be beneficial to be able to determine the progress of the task. I wanted to gauge the interest in having this feature before implementing it. My initial thoughts would be to add a field into the TaskState struct which would hold any metadata on the task. 

``` go
type TaskState struct {
  TaskUUID string
  State    string
  Result   *TaskResult
  Metadata map[interface{}]interface{}
  Error    string
}
```

There could then be a flag set in the task signature that would tell the worker to pass along a function that would be used by the task to set it's metadata.

``` go
type TaskSignature struct {
  UUID           string
  Name           string
  RoutingKey     string
  GroupUUID      string
  GroupTaskCount int
  Args           []TaskArg
  Immutable      bool
  HasMetadata    bool // tells worker to pass along a function to update metadata
  OnSuccess      []*TaskSignature
  OnError        []*TaskSignature
  ChordCallback  *TaskSignature
}
```

**Comment by RichardKnop** [comment]
@scotwells Hi Scott. Thanks. This actually sounds like a pretty useful feature to have. I would definitely like to implement something like this.

I haven't had much time to work on this library lately but eventually when I will have some spare time it would be something I might look at. Also if you want to submit a patch which implements something along these lines, feel free to do so.
