### ISSUE TITLE
Add logic to query current tasks in a queue

### ISSUE THREAD

**Issue by kcoleman731** [RichardKnop/machinery#80]
@RichardKnop been working with Machinery for a few months now and it is really great. Thank you so much for your work on the project!

I am interested in the ability to query a broker for tasks that are currently enqueued. I've searched through the project and don't believe this is currently supported. 

Unless I am mistaken, would you consider a PR that provides this functionality? I'm interested in this for testing purposes. IE I want to test some behavior that should publish a few tasks, then verify that they actually made it to the queue with the appropriate data. 

For ex, I have the following implemented on a fork for the `redis` `broker`. 
```
// PendingMessages returns a slice of task.Signatures currently enqueued.
func (redisBroker *RedisBroker) PendingMessages() ([]*signatures.TaskSignature, error) {
	conn, err := redisBroker.open()
	if err != nil {
		return nil, fmt.Errorf("Dial: %s", err)
	}
	defer conn.Close()

	bytes, err := conn.Do("LRANGE", redisBroker.config.DefaultQueue, 0, 10)
	if err != nil {
		fmt.Printf("Error: %v\n", err)
		return nil, err
	}
	results, err := redis.ByteSlices(bytes, err)
	if err != nil {
		fmt.Printf("Error: %v\n", err)
		return nil, err
	}

	var taskSignatures []*signatures.TaskSignature
	for _, result := range results {
		var taskSignature signatures.TaskSignature
		if err := json.Unmarshal(result, &taskSignature); err != nil {
			return nil, err
		}
		taskSignatures = append(taskSignatures, &taskSignature)
	}
	return taskSignatures, nil
}
```

I have additionally implement a function to purge a queue, which is also useful for testing. 
```
// PurgeQueue
func (redisBroker *RedisBroker) PurgeQueue() error {
	conn, err := redisBroker.open()
	if err != nil {
		return nil
	}
	defer conn.Close()

	_, err = conn.Do("DEL", redisBroker.config.DefaultQueue)
	return err
}
```

Would love to know your thoughts on the above.

**Comment by RichardKnop** [comment]
@kcoleman731 Could you create a PR for this? I think this would be a useful method to add to broker interface. However it would need to be supported by RabbitMQ too before it can get merged.

If you open a PR with your Redis implementation, I would try and add RabbitMQ equivalent.

**Comment by RichardKnop** [comment]
@kcoleman731 I have added this to the master branch with a small change. The method takes `queue` parameter and is named a bit differently. See: https://github.com/RichardKnop/machinery/blob/master/v1/brokers/interfaces.go#L14
