### ISSUE TITLE
Worker's concurrency limit

### ISSUE THREAD

**Issue by zhulik** [RichardKnop/machinery#83]
Hi, is there way to limit count of concurrent tasks running on one worker server? For example: I know, thar server A is slow, but server B is fast and i want to server B perform more tasks than server A. I want to told machinery worker that it can perform only 10 goroutins on server A, and 20 on server B.

Or another method: on servers i have some metric(GPU memory usage) and i want to configure worker to accept new tasks only if that metric is low.

Any suggestions?
Thanks!

**Comment by RichardKnop** [comment]
The first use case could be supported. We could add a parameter so worked would only consume a new task if it is processing less than N tasks at the moment. That seems like it could be done.

The second use case (with GPU or other metric) sounds more difficult to implement.

**Comment by zhulik** [comment]
You can implement this feature as user-defined function, with simple interface
```go
type acceptNewTask() bool
```
By default it will be like this
```go
func acceptNewTask() bool {
    return currentActiveTasks < n
}
```

And allow users to implement his own functions, based on his requirements

**Comment by hphilipps** [comment]
PR #111 added a config option to limit the number of worker instances.
