### ISSUE TITLE
Runtime Error: index out of range

### ISSUE THREAD

**Issue by vampirekiss** [RichardKnop/machinery#87]
file: ./worker.go
line: 139
```
if results[1].IsNil() 
```

this code on my machine will got an error "Error = runtime error: index out of range"

value of "results" is ``[<int Value>]``

go version: go1.6.3 darwin/amd64
 
task:
```
func Add(a int, b int) int {
	return a + b
}
```
worker:
```
task := signatures.TaskSignature{
		Name: "add",
		Args: []signatures.TaskArg{
			{
				Type:  "int",
				Value: 1,
			},
			{
				Type:  "int",
				Value: 1,
			},
		},
	}
_, sendTaskErr := server.SendTask(&task)
```

**Comment by vampirekiss** [comment]
my wrong, forgot it

**Comment by dokterbob** [comment]
@vampirekiss What was the problem here, in the end? I'm running into the same (probably similar) error.

**Comment by RichardKnop** [comment]
Your task needs to return second argument, an error. I believe that might be it.

**Comment by dokterbob** [comment]
I discovered what caused the problem, though I'm not sure whether it's a feature or a bug.

It seems that machinery assumes that a return argument (besides an error) is required, whereas in my application no return value is needed. Perhaps machinery should not assume there to be non-error return arguments or this could be documented better.
