### ISSUE TITLE
Feature Request: Pluggable Logger

### ISSUE THREAD

**Issue by mehcode** [RichardKnop/machinery#88]
Something simple where we can have this library use a logger that follows the standard interface would be good. 

I'm looking to use logrus to hide a good chunk of the `printf` spam that I get from using this library.

**Comment by RichardKnop** [comment]
@mehcode Would you like to propose a PR? I agree that logging needs to be done in a more sensible way. There should be a way to configure custom loggers.

**Comment by mehcode** [comment]
Oh It's definitely something I wouldn't mind contributing to; just don't expect something fast (I don't often get time to work on things like this though I do enjoy it).

---

I'd propose the following -- change `Config`  to accept a `Logger StdLogger` (interface type copied out from logrus -- https://github.com/Sirupsen/logrus/blob/master/logrus.go#L97-L109 ).

Then its just a matter of propagating that everywhere that needs it ( from a quick poke I'm assuming that config is available in most places as is ).

**Comment by ryanbaer** [comment]
+1

**Comment by RichardKnop** [comment]
@ryanbaer @mehcode https://github.com/RichardKnop/machinery/pull/99

**Comment by RichardKnop** [comment]
Merged

**Comment by RichardKnop** [comment]
@ryanbaer @mehcode documented here: https://github.com/RichardKnop/machinery#custom-logger
