### ISSUE TITLE
Feature Request: Delay task 

### ISSUE THREAD

**Issue by owenhaynes** [RichardKnop/machinery#91]
Ability to delay the tasks for processing e.g run task in 5 Min.

Could be implemented by adding a Execute Time to the task signature, and by user a helper method e.g

``` go
func (t *TaskSignature) Delay(d time.Duration) 
```

When the worker gets the task, it holds onto it until the execution time and then runs it. 

You want a store a time to execute and not just the delay as you want to guarantee that the task is run as close as possible to it, If the worker crashes the delay would start again otherwise.

**Comment by RichardKnop** [comment]
A good concept and I agree in principal. 

This could be supported natively by AMQP. You can schedule a delayed task. Redis broker also supports delayed tasks I believe.

So this could be implemented in a native way with both AMQP and Redis which is good as I am trying to keep the library behaviour consistent with different brokers / backends.

> You want a store a time to execute and not just the delay as you want to guarantee that the task is run as close as possible to it, If the worker crashes the delay would start again otherwise.

This would be taken care of by RabbitMQ / Redis process so machinery worker crashing and restarting should not matter as the logic will be handle by the broker.

Just need to confirm that both AMQP and Redis delayed tasks support setting a time when to free message to be consumed and not just some delay period.

**Comment by owenhaynes** [comment]
I thought rabbit required installing a plugin for delayed tasks, the plugin
then requires a header being applied to tasks with the delay

**Comment by RichardKnop** [comment]
If it requires a plugin then I wonder how would this work.

We need to store the execution time somewhere. So if you are using AMQP for both broker and backend this is a bit of a problem.

You can use a hack of storing the execution in a unique queue, something like `task_id_execute_at`. The message is gone once you read it form queue.

See this comments in AMQP backend: https://github.com/RichardKnop/machinery/blob/master/v1/backends/amqp.go#L3

I have implemented it in the same way Celery does it (a similar Python library) but it's quite hacky.

What Celery actually does they have a `celery-beat` process which allows you to schedule tasks.

Perhaps machinery might need something like this. A separate executable, e.g. `machinery-scheduler` to take care of this.

What do you think.

**Comment by owenhaynes** [comment]
I do not think its a good idea to have another process to be able to delay random run tasks. Only ever used redis for celery backend and AMQP for the broker. So not seen any of the flaws of AMQP as a backend.

Could do something like this https://ivanyu.me/blog/2015/02/16/delayed-message-delivery-in-rabbitmq/ for AMQP backends?

I agree that it make sense to have something similar to celery-beat if you have predefined tasks which need to be run at set times like clean up routines. A delayed task would not come under this.

**Comment by RichardKnop** [comment]
@owenhaynes Agreed. Delaying tasks should be part of the main process. If you have a solid idea how to implement this, PR's welcome!

Scheduling tasks (something like CRON) could come later and probably be a separate process.

**Comment by kavirajk** [comment]
I think we don't need either CRON or delayed-message-delivery-in-rabbitmq as suggested by @owenhaynes for delay task.

We can do the way celery does it. Point to note here is celery doesn't use celery-beat for delayed task. It uses beat only for periodic tasks (CRON).

The way actually cerely handles is via simple kwargs eta=<to-be-executed-time>. refer here http://docs.celeryproject.org/en/latest/userguide/calling.html#eta-and-countdown.

After digging into the celery code, just figured out celery is using "unacknowlege" feature of Rabbitmq to get this done. https://github.com/celery/celery/blob/master/celery/worker/strategy.py#L115-L127

Simple idea is, Whenever consumer consumes task from queue, it checks for key "eta" in the body of the message, then consumer won't acknowledge till the execution time is reached. So the task remains in the queue. 

Once the "execution time" is reached, consumer acknowledges it and execute the task.

This seems like the good idea. I think we do the same thing. What do u think guys @RichardKnop @owenhaynes

**Comment by RichardKnop** [comment]
@kavirajk Your proposed solution makes sense! This seems like it might not be that difficult to implement. Feel free to submit a PR if you need this fast :)

**Comment by kavirajk** [comment]
@RichardKnop I think I can pick this up coming week.

**Comment by kavirajk** [comment]
@RichardKnop I had a second thought while implementing this feature,

Why don't we just use time.Timer feature to delay the task

example: To delay Add task to 10 seconds, we can write in the following way

```go
// Add ...
func Add(args ...int64) (int64, error) {
	t := time.NewTimer(10 * time.Second)
	<-t.C
	sum := int64(0)
	for _, arg := range args {
		sum += arg
	}
	return sum, nil
}

```
@owenhaynes what do u think?

**Comment by brannon** [comment]
One use for Celery delayed tasks is when retrying a task (e.g. `task.retry(countdown=30)`).  That could be implemented via the "eta" / "unacknowledge" approach pretty easily if you are just re-queueing the same task with an eta.

**Comment by gonzalobustos** [comment]
+1 
I'm really interested in this feature.

**Comment by tspecht** [comment]
Any update on this?

**Comment by RichardKnop** [comment]
No update from me yet unfortunately.

**Comment by RichardKnop** [comment]
@owenhaynes @kavirajk @tspecht @gonzalobustos I have added support for delayed tasks. Currently it only works with AMPQ broker though.

See here: https://github.com/RichardKnop/machinery#delayed-tasks

**Comment by tspecht** [comment]
Awesome, thanks a lot, exactly what I needed!
