### ISSUE TITLE
Publish Message error when use redis as broker

### ISSUE THREAD

**Issue by chennqqi** [RichardKnop/machinery#92]
Publish Message: write tcp 192.168.56.1:14302->192.168.56.6:6379: wsasend: An existing connection was forcibly closed by the remote host.

I start a chord task which has more than 1500 subtask， one of each contains a 1K bytes message.

**Comment by chennqqi** [comment]
This error may be redigo's bug

**Comment by RichardKnop** [comment]
@chennqqi I am not sure what is causing the error. This needs to be investigated further.

FYI: https://github.com/RichardKnop/machinery/issues/30

There is a bug with chords on Redis. They don't work correctly at the moment. So could be related.

**Comment by chennqqi** [comment]
Yeah, I use chords on Redis. I found workers 'ESTABLISHED' too many connections with broker&backend. so, that's way publishing tasks  failed(wsasend: An existing connection was forcibly closed by the remote host).  Each subtask of a chord has a connection with broker&backend.

**Comment by RichardKnop** [comment]
I see. Can you make a PR to fix this?

**Comment by chennqqi** [comment]
ok. I will have a try. or I sugguest using nsq or nats instand of redis...
Now, i simply package a chord task (with a lot of subtask) as a standard task to escape this problem.

**Comment by FuzzyStatic** [comment]
Was there ever a solution or fix for this issue?
