### ISSUE TITLE
Could not send task

### ISSUE THREAD

**Issue by saggit** [RichardKnop/machinery#94]
Hi,
    When I test with the example, I got this error:
```sh
Could not send task: Set State Pending: Queue Declare: Exception (406) Reason: "PRECONDITION_FAILED - invalid arg 'x-message-ttl' for queue 'task_5d2b652d-8428-4834-8c5e-bb4c6bc94d50' in vhost '/': {value_negative,-694967296}"
panic: Could not send task: Set State Pending: Queue Declare: Exception (406) Reason: "PRECONDITION_FAILED - invalid arg 'x-message-ttl' for queue 'task_5d2b652d-8428-4834-8c5e-bb4c6bc94d50' in vhost '/': {value_negative,-694967296}"
```

I am running RabbitMQ 3.6.4 on my mac and use the default exampleconfig.yml,

I also do search, the problem seems to be  declare it again with a x-message-ttl, so i remove this line

```sh
results_expire_in: 3600000
```
then it works fine,  is there other way to solve this problem?

thanks.

**Comment by RichardKnop** [comment]
@saggit 

> The PRECONDITION_FAILED is because the queue has already been declared without x-message-ttl and when trying to declare it again with a x-message-ttl, the declare fails because the arguments of the declares are different. Try deleting the queue, then declare it with a int32 x-message-ttl.

Source: https://github.com/streadway/amqp/issues/60#issuecomment-18119437

**Comment by saggit** [comment]
thanks.

**Comment by Blogoslov** [comment]
@RichardKnop Speaking friendly I don't get how the queue can be declared without x-message-ttl when server and sender before initialization has and read the same config file and set the same option 'results_expire_in:' which mentioned in the config file.

And I don't understand how it can be fixed? Where and how should I declare int32 x-message-ttl? Could you please explain with small example?

Thanks  and regards.
