### ISSUE TITLE
Configurable prefetch count

### ISSUE THREAD

**Issue by dokterbob** [RichardKnop/machinery#95]
Having machinery run with tasks that have a long (+1 minute) I/O wait gets tedeously slow. It would be great to be able to increase the prefetch count.

For APMQ, this lives here:
https://github.com/RichardKnop/machinery/blob/fdb5d381481abc9a365bb091a4a58bdd5b23c610/v1/brokers/amqp.go#L66

**Comment by RichardKnop** [comment]
@dokterbob I agree. Do you want to create a PR? Probably another field in config so this can be configured instead of current state when it's hardcoded to 3.

**Comment by dokterbob** [comment]
I have been considering it, but for my particular application I think I might be better off interfacing with AMQP directly - I might want to do stuff like dynamically requesting more work for slower tasks and don’t need results at all.

Should I change my mind, you can be sure to find yourself a pull request - although that would be my first contribution to a Go project. :)

**Comment by RichardKnop** [comment]
@dokterbob Fair enough. For many use cases interfacing directly with AMQP is better than using this library. Depends on what problem you are solving :)

**Comment by dokterbob** [comment]
That's indeed what I ended up doing. :)

Thanks. :)
