### ISSUE TITLE
Feature print stack on panic

### ISSUE THREAD

**Issue by owenhaynes** [RichardKnop/machinery#96]
Print the stack when panic happens when processing task.

At the moment the stack is lost when a panic happens inside of a task. I do not know if its best to enforce people to put there own handling for panics or just update the global worker panic recover to have a stack trace, or both?

At the moment you can get into situations like this:
> 2016/08/18 07:56:45 Failed processing task_225ef62d-6c6b-42dd-9bce-d91d4c7edea9. Error = runtime error: invalid memory address or nil pointer dereference
> 

Which makes it impossible to debug.

If its a good idea to put this in the global worker recover let me know and with make a pull request for it.

**Comment by RichardKnop** [comment]
@owenhaynes This is a good idea. Should be part of the worker processing logic. Can you make a PR?

**Comment by rooty123** [comment]
Any ideas how to walk around it at the present time? 
I cannot find what's the reason of the error:

Error = runtime error: invalid memory address or nil pointer dereference

**Comment by RichardKnop** [comment]
@rooty123 @owenhaynes This has been fixed now: https://github.com/RichardKnop/machinery/pull/98
